/*
Copyright 2024 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package license implements the `license` command group: `add` prepends the
// Flant CE license header to files that need one, and `check` fails when a file
// that should carry a header does not.
package license

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/deckhouse/virtualization/tools/modtools/internal/report"
)

func NewCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "license",
		Short: "Manage Flant CE license headers",
	}

	var addDir string
	add := &cobra.Command{
		Use:   "add",
		Short: "Add the Flant CE license header to files that need one",
		RunE: func(_ *cobra.Command, _ []string) error {
			return report.ExitErr(walk(addDir, true))
		},
	}
	add.Flags().StringVar(&addDir, "directory", "./", "Directory to process.")

	var checkDir string
	check := &cobra.Command{
		Use:   "check",
		Short: "Verify that files requiring a license header have one",
		RunE: func(_ *cobra.Command, _ []string) error {
			return report.ExitErr(walk(checkDir, false))
		},
	}
	check.Flags().StringVar(&checkDir, "directory", "./", "Directory to check.")

	cmd.AddCommand(add, check)
	return cmd
}

var licenseText = fmt.Sprintf(`Copyright %d Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
`, time.Now().Year())

var (
	goLicense         = "/*\n" + licenseText + "*/\n"
	bashPythonLicense = "# " + strings.ReplaceAll(strings.TrimSpace(licenseText), "\n", "\n# ") + "\n"
)

// fileToCheckRe matches files that require a license header:
//   - Ends with .go, .sh, .py
//   - Any file without an extension in its last path segment
//   - Files under .github/{scripts,workflows,workflow_templates} ending with .js, .yml, .yaml or .sh
var fileToCheckRe = regexp.MustCompile(`\.go$|/[^/.]+$|\.sh$|\.py$|\.github/(scripts|workflows|workflow_templates)/.+\.(js|yml|yaml|sh)$`)

// fileToSkipRe matches paths that must be skipped:
//   - Non-source trees: .git/, /docs/, vendor/, node_modules/, testdata/, and
//     vendored upstream copies (a /__ path segment, e.g. images/*/__kubevirt)
//   - Dockerfile, Makefile, Taskfile, LICENSE, .github/CODEOWNERS
//   - geohash.lua, bashrc, inputrc, modules_menu_skip
var fileToSkipRe = regexp.MustCompile(`geohash\.lua$|\.git/|/vendor/|/node_modules/|/testdata/|/__|\.github/CODEOWNERS$|Dockerfile$|Makefile$|Taskfile|/docs/|bashrc$|inputrc$|modules_menu_skip$|LICENSE$`)

var CELicenseRe = regexp.MustCompile(`(?s)[/#{!-]*(\s)*Copyright 20\d{2} Flant JSC[-!}\s\n#/]*
[/#{!-]*(\s)*Licensed under the Apache License, Version 2.0 \(the "License"\);[-!}\n]*
[/#{!-]*(\s)*you may not use this file except in compliance with the License.[-!}\n]*
[/#{!-]*(\s)*You may obtain a copy of the License at[-!}\n\s#/]*
[/#{!-]*(\s)*http://www.apache.org/licenses/LICENSE-2.0[-!}\n\s#/]*
[/#{!-]*(\s)*Unless required by applicable law or agreed to in writing, software[-!}\n]*
[/#{!-]*(\s)*distributed under the License is distributed on an "AS IS" BASIS,[-!}\n]*
[/#{!-]*(\s)*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.[-!}\n]*
[/#{!-]*(\s)*See the License for the specific language governing permissions and[-!}\n]*
[/#{!-]*(\s)*limitations under the License.[-!}\n]{0,1}`)

var (
	copyrightOrAutogenRe = regexp.MustCompile(`Copyright The|autogenerated|DO NOT EDIT`)
	copyrightRe          = regexp.MustCompile(`Copyright`)
	flantRe              = regexp.MustCompile(`Flant|Deckhouse`)
)

func getLicenseForFile(filePath string) string {
	switch filepath.Ext(filePath) {
	case ".go":
		return goLicense
	case ".py", ".sh", ".bash", ".zsh", ".yaml", ".yml":
		return bashPythonLicense
	default:
		return ""
	}
}

func isShebangLine(line string) bool {
	return strings.HasPrefix(line, "#!")
}

type licenseKind string

const (
	kindNone    licenseKind = ""
	kindCE      licenseKind = "CE"
	kindAutogen licenseKind = "autogenerated"
	kindFlant   licenseKind = "Flant"
	kindOther   licenseKind = "other"
)

// detectLicense categorizes the header a file already carries. Order matters:
// the exact CE header is checked before the looser Flant/copyright fallbacks.
func detectLicense(content []byte) licenseKind {
	switch {
	case CELicenseRe.Match(content):
		return kindCE
	case copyrightOrAutogenRe.Match(content):
		return kindAutogen
	case flantRe.Match(content):
		return kindFlant
	case copyrightRe.Match(content):
		return kindOther
	default:
		return kindNone
	}
}

// result accumulates the outcome of a walk so it can be summarized instead of
// printing one line per file. Only the actionable failures (missing headers in
// check mode, read/write errors) keep their paths; everything else is a count.
type result struct {
	scanned     int
	ce          int
	nonCE       int      // files carrying a non-CE / foreign header
	added       int      // add mode: license inserted
	unsupported int      // no header and unknown comment style (cannot classify)
	missing     []string // check mode: known source file with no header (the failures)
	failed      []string // read/write errors ("path: reason")
}

// walk visits dir, categorizing every candidate file. When add is true it
// prepends the license to files that lack one. Returns 1 when the run found
// actionable problems (missing/unsupported/errors).
func walk(dir string, add bool) int {
	directory, err := filepath.Abs(dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Cannot get absolute path of directory: %v\n", err)
		return 1
	}
	fmt.Println("Directory:", directory)

	files, err := candidateFiles(directory)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}

	res := &result{}
	for _, filePath := range files {
		if fileToSkipRe.MatchString(filePath) || !fileToCheckRe.MatchString(filePath) {
			continue
		}
		info, err := os.Lstat(filePath)
		if err != nil || info.IsDir() || !info.Mode().IsRegular() {
			continue
		}
		res.process(filePath, info.Mode().Perm(), add)
	}
	res.print(add)
	return res.exitCode()
}

// candidateFiles lists absolute paths under dir that git does not ignore
// (tracked plus untracked-but-not-ignored, so newly created files are still
// covered). It falls back to a full filesystem walk when dir is not inside a
// git work tree.
func candidateFiles(dir string) ([]string, error) {
	out, err := exec.Command("git", "-C", dir, "ls-files", "--cached", "--others", "--exclude-standard", "-z").Output()
	if err != nil {
		return walkAll(dir)
	}
	var files []string
	for _, rel := range strings.Split(strings.TrimRight(string(out), "\x00"), "\x00") {
		if rel != "" {
			files = append(files, filepath.Join(dir, rel))
		}
	}
	return files, nil
}

func walkAll(dir string) ([]string, error) {
	var files []string
	err := filepath.Walk(dir, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			files = append(files, p)
		}
		return nil
	})
	return files, err
}

func (r *result) process(filePath string, mode os.FileMode, add bool) {
	r.scanned++

	content, err := os.ReadFile(filePath)
	if err != nil {
		r.failed = append(r.failed, fmt.Sprintf("%s: read: %v", filePath, err))
		return
	}

	switch detectLicense(content) {
	case kindCE:
		r.ce++
		return
	case kindAutogen, kindFlant, kindOther:
		r.nonCE++
		return
	}

	// No header at all.
	licenseFileText := getLicenseForFile(filePath)
	if licenseFileText == "" {
		// Unknown comment style (e.g. an extension-less data file): we can
		// neither insert a header nor confidently call it a missing license.
		r.unsupported++
		return
	}
	if !add {
		r.missing = append(r.missing, filePath)
		return
	}
	if err := writeWithLicense(filePath, content, licenseFileText, mode); err != nil {
		r.failed = append(r.failed, fmt.Sprintf("%s: write: %v", filePath, err))
		return
	}
	r.added++
}

// writeWithLicense prepends licenseText to content, keeping a shebang first, and
// preserves the file's original permissions (so executable scripts stay +x).
func writeWithLicense(filePath string, content []byte, licenseText string, mode os.FileMode) error {
	var buf bytes.Buffer
	firstLine, restOfFile, _ := strings.Cut(string(content), "\n")
	if isShebangLine(firstLine) {
		buf.WriteString(firstLine)
		buf.WriteString("\n\n")
		buf.WriteString(licenseText)
		buf.WriteString(restOfFile)
	} else {
		buf.WriteString(licenseText)
		buf.WriteString("\n")
		buf.Write(content)
	}
	return os.WriteFile(filePath, buf.Bytes(), mode)
}

// exitCode fails only on real problems: source files missing a header (check
// mode) or read/write errors. Unclassified files are informational.
func (r *result) exitCode() int {
	if len(r.missing)+len(r.failed) > 0 {
		return 1
	}
	return 0
}

func (r *result) print(add bool) {
	printList := func(title string, items []string) {
		if len(items) == 0 {
			return
		}
		fmt.Printf("\n%s (%d):\n", title, len(items))
		for _, it := range items {
			fmt.Printf("  * %s\n", it)
		}
	}

	// Only the actionable failures keep their paths; everything else is a count
	// in the summary below.
	if !add {
		printList("Missing license", r.missing)
	}
	printList("Errors", r.failed)

	fmt.Printf("\nSummary: %d files scanned, %d with CE license", r.scanned, r.ce)
	if r.nonCE > 0 {
		fmt.Printf(", %d with a non-CE license", r.nonCE)
	}
	if add {
		fmt.Printf(", %d added", r.added)
	} else {
		fmt.Printf(", %d missing", len(r.missing))
	}
	if r.unsupported > 0 {
		fmt.Printf(", %d unclassified", r.unsupported)
	}
	if len(r.failed) > 0 {
		fmt.Printf(", %d errors", len(r.failed))
	}
	fmt.Println(".")
}
