package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func isShebangLine(line string) bool {
	return strings.HasPrefix(line, "#!")
}

func closeFile(f *os.File) {
	err := f.Close()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func getLicenseForFile(filePath string) string {
	switch filepath.Ext(filePath) {
	case ".go":
		return goLicense
	case ".py", ".sh", ".bash", ".zsh":
		return bashPythonLicense
	default:
		return ""
	}
}

func checkLicense(fullContent []byte, filePath string) (Message, bool) {
	if CELicenseRe.MatchString(string(fullContent)) {
		msg := NewSkip(filePath, "File already contains CE license")
		return msg, true
	}

	if copyrightOrAutogenRe.MatchString(string(fullContent)) {
		msg := NewSkip(filePath, "File already contains autogenerated license")
		return msg, true
	}

	if flantRe.MatchString(string(fullContent)) {
		msg := NewSkip(filePath, "File already contains Flant license")
		return msg, true
	}

	if copyrightRe.MatchString(string(fullContent)) {
		msg := NewSkip(filePath, "File contains other license")
		return msg, true
	}

	return Message{}, false
}

func addLicenseToFile(filePath, license string) Message {
	f, err := os.Open(filePath)
	if err != nil {
		message := NewError(filepath.Base(filePath), "Error opening file", err.Error())
		return message
	}
	defer closeFile(f)

	reader := bufio.NewReader(f)
	//firstLine, err := reader.ReadString('\n')
	//if err != nil && err.Error() != "EOF" {
	//	message := NewError(filepath.Base(filePath), "Failed to read first line", err.Error())
	//	return message
	//}

	fullContent, err := io.ReadAll(reader)
	if err != nil {
		message := NewError(filepath.Base(filePath), "Failed to read rest of file", err.Error())
		return message
	}

	firstLine, restOfFile, _ := strings.Cut(string(fullContent), "\n")
	//fullContent := append([]byte(firstLine), restOfFile...)

	message, lic := checkLicense(fullContent, filePath)
	//var newContent []byte
	var newContent bytes.Buffer

	if !lic {
		if isShebangLine(firstLine) {
			newContent.Write([]byte(firstLine + "\n\n"))
			newContent.Write([]byte(license))
			newContent.Write([]byte(restOfFile))
			//newContent = append([]byte(firstLine+"\n"), append([]byte(license), restOfFile...)...)
		} else {
			newContent.Write([]byte(license))
			newContent.Write([]byte(restOfFile))
			//newContent.Write([]byte(firstLine + "\n"))
			//newContent = append([]byte(license), append([]byte(firstLine+"\n"), restOfFile...)...)
			//newContent = append([]byte(license), append([]byte(firstLine+"\n"), restOfFile...)...)
		}
	} else {
		return message
	}

	err = os.WriteFile(filePath, newContent.Bytes(), 0644)

	if err != nil {
		message = NewError(filepath.Base(filePath), "Failed to write file", err.Error())
		return message
	}

	return NewAdd(filepath.Base(filePath))
	//return os.WriteFile(filePath, newContent, 0644)
}
