//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	componentconfig "github.com/deckhouse/virtualization-controller/pkg/config/apis/componentconfig"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BaseGCSettings)(nil), (*componentconfig.BaseGCSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BaseGCSettings_To_componentconfig_BaseGCSettings(a.(*BaseGCSettings), b.(*componentconfig.BaseGCSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.BaseGCSettings)(nil), (*BaseGCSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_BaseGCSettings_To_v1alpha1_BaseGCSettings(a.(*componentconfig.BaseGCSettings), b.(*BaseGCSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DVCR)(nil), (*componentconfig.DVCR)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DVCR_To_componentconfig_DVCR(a.(*DVCR), b.(*componentconfig.DVCR), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.DVCR)(nil), (*DVCR)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_DVCR_To_v1alpha1_DVCR(a.(*componentconfig.DVCR), b.(*DVCR), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GarbageCollector)(nil), (*componentconfig.GarbageCollector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GarbageCollector_To_componentconfig_GarbageCollector(a.(*GarbageCollector), b.(*componentconfig.GarbageCollector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.GarbageCollector)(nil), (*GarbageCollector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_GarbageCollector_To_v1alpha1_GarbageCollector(a.(*componentconfig.GarbageCollector), b.(*GarbageCollector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ImportSettings)(nil), (*componentconfig.ImportSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ImportSettings_To_componentconfig_ImportSettings(a.(*ImportSettings), b.(*componentconfig.ImportSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.ImportSettings)(nil), (*ImportSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_ImportSettings_To_v1alpha1_ImportSettings(a.(*componentconfig.ImportSettings), b.(*ImportSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Ingress)(nil), (*componentconfig.Ingress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Ingress_To_componentconfig_Ingress(a.(*Ingress), b.(*componentconfig.Ingress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.Ingress)(nil), (*Ingress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_Ingress_To_v1alpha1_Ingress(a.(*componentconfig.Ingress), b.(*Ingress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualDiskStorageClassSettings)(nil), (*componentconfig.VirtualDiskStorageClassSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualDiskStorageClassSettings_To_componentconfig_VirtualDiskStorageClassSettings(a.(*VirtualDiskStorageClassSettings), b.(*componentconfig.VirtualDiskStorageClassSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.VirtualDiskStorageClassSettings)(nil), (*VirtualDiskStorageClassSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_VirtualDiskStorageClassSettings_To_v1alpha1_VirtualDiskStorageClassSettings(a.(*componentconfig.VirtualDiskStorageClassSettings), b.(*VirtualDiskStorageClassSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualImageStorageClassSettings)(nil), (*componentconfig.VirtualImageStorageClassSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualImageStorageClassSettings_To_componentconfig_VirtualImageStorageClassSettings(a.(*VirtualImageStorageClassSettings), b.(*componentconfig.VirtualImageStorageClassSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.VirtualImageStorageClassSettings)(nil), (*VirtualImageStorageClassSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_VirtualImageStorageClassSettings_To_v1alpha1_VirtualImageStorageClassSettings(a.(*componentconfig.VirtualImageStorageClassSettings), b.(*VirtualImageStorageClassSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualizationControllerConfiguration)(nil), (*componentconfig.VirtualizationControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualizationControllerConfiguration_To_componentconfig_VirtualizationControllerConfiguration(a.(*VirtualizationControllerConfiguration), b.(*componentconfig.VirtualizationControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.VirtualizationControllerConfiguration)(nil), (*VirtualizationControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_VirtualizationControllerConfiguration_To_v1alpha1_VirtualizationControllerConfiguration(a.(*componentconfig.VirtualizationControllerConfiguration), b.(*VirtualizationControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualizationControllerConfigurationSpec)(nil), (*componentconfig.VirtualizationControllerConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualizationControllerConfigurationSpec_To_componentconfig_VirtualizationControllerConfigurationSpec(a.(*VirtualizationControllerConfigurationSpec), b.(*componentconfig.VirtualizationControllerConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.VirtualizationControllerConfigurationSpec)(nil), (*VirtualizationControllerConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_VirtualizationControllerConfigurationSpec_To_v1alpha1_VirtualizationControllerConfigurationSpec(a.(*componentconfig.VirtualizationControllerConfigurationSpec), b.(*VirtualizationControllerConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BaseGCSettings_To_componentconfig_BaseGCSettings(in *BaseGCSettings, out *componentconfig.BaseGCSettings, s conversion.Scope) error {
	out.TTL = in.TTL
	out.Schedule = in.Schedule
	return nil
}

// Convert_v1alpha1_BaseGCSettings_To_componentconfig_BaseGCSettings is an autogenerated conversion function.
func Convert_v1alpha1_BaseGCSettings_To_componentconfig_BaseGCSettings(in *BaseGCSettings, out *componentconfig.BaseGCSettings, s conversion.Scope) error {
	return autoConvert_v1alpha1_BaseGCSettings_To_componentconfig_BaseGCSettings(in, out, s)
}

func autoConvert_componentconfig_BaseGCSettings_To_v1alpha1_BaseGCSettings(in *componentconfig.BaseGCSettings, out *BaseGCSettings, s conversion.Scope) error {
	out.TTL = in.TTL
	out.Schedule = in.Schedule
	return nil
}

// Convert_componentconfig_BaseGCSettings_To_v1alpha1_BaseGCSettings is an autogenerated conversion function.
func Convert_componentconfig_BaseGCSettings_To_v1alpha1_BaseGCSettings(in *componentconfig.BaseGCSettings, out *BaseGCSettings, s conversion.Scope) error {
	return autoConvert_componentconfig_BaseGCSettings_To_v1alpha1_BaseGCSettings(in, out, s)
}

func autoConvert_v1alpha1_DVCR_To_componentconfig_DVCR(in *DVCR, out *componentconfig.DVCR, s conversion.Scope) error {
	out.AuthSecret = in.AuthSecret
	out.CertsSecret = in.CertsSecret
	out.RegistryURL = in.RegistryURL
	out.InsecureTLS = in.InsecureTLS
	return nil
}

// Convert_v1alpha1_DVCR_To_componentconfig_DVCR is an autogenerated conversion function.
func Convert_v1alpha1_DVCR_To_componentconfig_DVCR(in *DVCR, out *componentconfig.DVCR, s conversion.Scope) error {
	return autoConvert_v1alpha1_DVCR_To_componentconfig_DVCR(in, out, s)
}

func autoConvert_componentconfig_DVCR_To_v1alpha1_DVCR(in *componentconfig.DVCR, out *DVCR, s conversion.Scope) error {
	out.AuthSecret = in.AuthSecret
	out.CertsSecret = in.CertsSecret
	out.RegistryURL = in.RegistryURL
	out.InsecureTLS = in.InsecureTLS
	return nil
}

// Convert_componentconfig_DVCR_To_v1alpha1_DVCR is an autogenerated conversion function.
func Convert_componentconfig_DVCR_To_v1alpha1_DVCR(in *componentconfig.DVCR, out *DVCR, s conversion.Scope) error {
	return autoConvert_componentconfig_DVCR_To_v1alpha1_DVCR(in, out, s)
}

func autoConvert_v1alpha1_GarbageCollector_To_componentconfig_GarbageCollector(in *GarbageCollector, out *componentconfig.GarbageCollector, s conversion.Scope) error {
	if err := Convert_v1alpha1_BaseGCSettings_To_componentconfig_BaseGCSettings(&in.VMOP, &out.VMOP, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BaseGCSettings_To_componentconfig_BaseGCSettings(&in.VMIMigration, &out.VMIMigration, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_GarbageCollector_To_componentconfig_GarbageCollector is an autogenerated conversion function.
func Convert_v1alpha1_GarbageCollector_To_componentconfig_GarbageCollector(in *GarbageCollector, out *componentconfig.GarbageCollector, s conversion.Scope) error {
	return autoConvert_v1alpha1_GarbageCollector_To_componentconfig_GarbageCollector(in, out, s)
}

func autoConvert_componentconfig_GarbageCollector_To_v1alpha1_GarbageCollector(in *componentconfig.GarbageCollector, out *GarbageCollector, s conversion.Scope) error {
	if err := Convert_componentconfig_BaseGCSettings_To_v1alpha1_BaseGCSettings(&in.VMOP, &out.VMOP, s); err != nil {
		return err
	}
	if err := Convert_componentconfig_BaseGCSettings_To_v1alpha1_BaseGCSettings(&in.VMIMigration, &out.VMIMigration, s); err != nil {
		return err
	}
	return nil
}

// Convert_componentconfig_GarbageCollector_To_v1alpha1_GarbageCollector is an autogenerated conversion function.
func Convert_componentconfig_GarbageCollector_To_v1alpha1_GarbageCollector(in *componentconfig.GarbageCollector, out *GarbageCollector, s conversion.Scope) error {
	return autoConvert_componentconfig_GarbageCollector_To_v1alpha1_GarbageCollector(in, out, s)
}

func autoConvert_v1alpha1_ImportSettings_To_componentconfig_ImportSettings(in *ImportSettings, out *componentconfig.ImportSettings, s conversion.Scope) error {
	out.ImporterImage = in.ImporterImage
	out.UploaderImage = in.UploaderImage
	out.BounderImage = in.BounderImage
	out.Requirements = in.Requirements
	return nil
}

// Convert_v1alpha1_ImportSettings_To_componentconfig_ImportSettings is an autogenerated conversion function.
func Convert_v1alpha1_ImportSettings_To_componentconfig_ImportSettings(in *ImportSettings, out *componentconfig.ImportSettings, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImportSettings_To_componentconfig_ImportSettings(in, out, s)
}

func autoConvert_componentconfig_ImportSettings_To_v1alpha1_ImportSettings(in *componentconfig.ImportSettings, out *ImportSettings, s conversion.Scope) error {
	out.ImporterImage = in.ImporterImage
	out.UploaderImage = in.UploaderImage
	out.BounderImage = in.BounderImage
	out.Requirements = in.Requirements
	return nil
}

// Convert_componentconfig_ImportSettings_To_v1alpha1_ImportSettings is an autogenerated conversion function.
func Convert_componentconfig_ImportSettings_To_v1alpha1_ImportSettings(in *componentconfig.ImportSettings, out *ImportSettings, s conversion.Scope) error {
	return autoConvert_componentconfig_ImportSettings_To_v1alpha1_ImportSettings(in, out, s)
}

func autoConvert_v1alpha1_Ingress_To_componentconfig_Ingress(in *Ingress, out *componentconfig.Ingress, s conversion.Scope) error {
	out.Host = in.Host
	out.TLSSecret = in.TLSSecret
	out.Class = in.Class
	return nil
}

// Convert_v1alpha1_Ingress_To_componentconfig_Ingress is an autogenerated conversion function.
func Convert_v1alpha1_Ingress_To_componentconfig_Ingress(in *Ingress, out *componentconfig.Ingress, s conversion.Scope) error {
	return autoConvert_v1alpha1_Ingress_To_componentconfig_Ingress(in, out, s)
}

func autoConvert_componentconfig_Ingress_To_v1alpha1_Ingress(in *componentconfig.Ingress, out *Ingress, s conversion.Scope) error {
	out.Host = in.Host
	out.TLSSecret = in.TLSSecret
	out.Class = in.Class
	return nil
}

// Convert_componentconfig_Ingress_To_v1alpha1_Ingress is an autogenerated conversion function.
func Convert_componentconfig_Ingress_To_v1alpha1_Ingress(in *componentconfig.Ingress, out *Ingress, s conversion.Scope) error {
	return autoConvert_componentconfig_Ingress_To_v1alpha1_Ingress(in, out, s)
}

func autoConvert_v1alpha1_VirtualDiskStorageClassSettings_To_componentconfig_VirtualDiskStorageClassSettings(in *VirtualDiskStorageClassSettings, out *componentconfig.VirtualDiskStorageClassSettings, s conversion.Scope) error {
	out.AllowedStorageClassNames = *(*[]string)(unsafe.Pointer(&in.AllowedStorageClassNames))
	out.DefaultStorageClassName = in.DefaultStorageClassName
	return nil
}

// Convert_v1alpha1_VirtualDiskStorageClassSettings_To_componentconfig_VirtualDiskStorageClassSettings is an autogenerated conversion function.
func Convert_v1alpha1_VirtualDiskStorageClassSettings_To_componentconfig_VirtualDiskStorageClassSettings(in *VirtualDiskStorageClassSettings, out *componentconfig.VirtualDiskStorageClassSettings, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualDiskStorageClassSettings_To_componentconfig_VirtualDiskStorageClassSettings(in, out, s)
}

func autoConvert_componentconfig_VirtualDiskStorageClassSettings_To_v1alpha1_VirtualDiskStorageClassSettings(in *componentconfig.VirtualDiskStorageClassSettings, out *VirtualDiskStorageClassSettings, s conversion.Scope) error {
	out.AllowedStorageClassNames = *(*[]string)(unsafe.Pointer(&in.AllowedStorageClassNames))
	out.DefaultStorageClassName = in.DefaultStorageClassName
	return nil
}

// Convert_componentconfig_VirtualDiskStorageClassSettings_To_v1alpha1_VirtualDiskStorageClassSettings is an autogenerated conversion function.
func Convert_componentconfig_VirtualDiskStorageClassSettings_To_v1alpha1_VirtualDiskStorageClassSettings(in *componentconfig.VirtualDiskStorageClassSettings, out *VirtualDiskStorageClassSettings, s conversion.Scope) error {
	return autoConvert_componentconfig_VirtualDiskStorageClassSettings_To_v1alpha1_VirtualDiskStorageClassSettings(in, out, s)
}

func autoConvert_v1alpha1_VirtualImageStorageClassSettings_To_componentconfig_VirtualImageStorageClassSettings(in *VirtualImageStorageClassSettings, out *componentconfig.VirtualImageStorageClassSettings, s conversion.Scope) error {
	out.AllowedStorageClassNames = *(*[]string)(unsafe.Pointer(&in.AllowedStorageClassNames))
	out.DefaultStorageClassName = in.DefaultStorageClassName
	out.StorageClassName = in.StorageClassName
	return nil
}

// Convert_v1alpha1_VirtualImageStorageClassSettings_To_componentconfig_VirtualImageStorageClassSettings is an autogenerated conversion function.
func Convert_v1alpha1_VirtualImageStorageClassSettings_To_componentconfig_VirtualImageStorageClassSettings(in *VirtualImageStorageClassSettings, out *componentconfig.VirtualImageStorageClassSettings, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualImageStorageClassSettings_To_componentconfig_VirtualImageStorageClassSettings(in, out, s)
}

func autoConvert_componentconfig_VirtualImageStorageClassSettings_To_v1alpha1_VirtualImageStorageClassSettings(in *componentconfig.VirtualImageStorageClassSettings, out *VirtualImageStorageClassSettings, s conversion.Scope) error {
	out.AllowedStorageClassNames = *(*[]string)(unsafe.Pointer(&in.AllowedStorageClassNames))
	out.DefaultStorageClassName = in.DefaultStorageClassName
	out.StorageClassName = in.StorageClassName
	return nil
}

// Convert_componentconfig_VirtualImageStorageClassSettings_To_v1alpha1_VirtualImageStorageClassSettings is an autogenerated conversion function.
func Convert_componentconfig_VirtualImageStorageClassSettings_To_v1alpha1_VirtualImageStorageClassSettings(in *componentconfig.VirtualImageStorageClassSettings, out *VirtualImageStorageClassSettings, s conversion.Scope) error {
	return autoConvert_componentconfig_VirtualImageStorageClassSettings_To_v1alpha1_VirtualImageStorageClassSettings(in, out, s)
}

func autoConvert_v1alpha1_VirtualizationControllerConfiguration_To_componentconfig_VirtualizationControllerConfiguration(in *VirtualizationControllerConfiguration, out *componentconfig.VirtualizationControllerConfiguration, s conversion.Scope) error {
	if err := Convert_v1alpha1_VirtualizationControllerConfigurationSpec_To_componentconfig_VirtualizationControllerConfigurationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VirtualizationControllerConfiguration_To_componentconfig_VirtualizationControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_VirtualizationControllerConfiguration_To_componentconfig_VirtualizationControllerConfiguration(in *VirtualizationControllerConfiguration, out *componentconfig.VirtualizationControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualizationControllerConfiguration_To_componentconfig_VirtualizationControllerConfiguration(in, out, s)
}

func autoConvert_componentconfig_VirtualizationControllerConfiguration_To_v1alpha1_VirtualizationControllerConfiguration(in *componentconfig.VirtualizationControllerConfiguration, out *VirtualizationControllerConfiguration, s conversion.Scope) error {
	if err := Convert_componentconfig_VirtualizationControllerConfigurationSpec_To_v1alpha1_VirtualizationControllerConfigurationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_componentconfig_VirtualizationControllerConfiguration_To_v1alpha1_VirtualizationControllerConfiguration is an autogenerated conversion function.
func Convert_componentconfig_VirtualizationControllerConfiguration_To_v1alpha1_VirtualizationControllerConfiguration(in *componentconfig.VirtualizationControllerConfiguration, out *VirtualizationControllerConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_VirtualizationControllerConfiguration_To_v1alpha1_VirtualizationControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_VirtualizationControllerConfigurationSpec_To_componentconfig_VirtualizationControllerConfigurationSpec(in *VirtualizationControllerConfigurationSpec, out *componentconfig.VirtualizationControllerConfigurationSpec, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.FirmwareImage = in.FirmwareImage
	out.VirtControllerName = in.VirtControllerName
	out.VirtualMachineCIDRs = *(*[]string)(unsafe.Pointer(&in.VirtualMachineCIDRs))
	out.VirtualMachineIPLeasesRetentionDuration = in.VirtualMachineIPLeasesRetentionDuration
	if err := Convert_v1alpha1_GarbageCollector_To_componentconfig_GarbageCollector(&in.GarbageCollector, &out.GarbageCollector, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VirtualImageStorageClassSettings_To_componentconfig_VirtualImageStorageClassSettings(&in.VirtualImageStorageClassSettings, &out.VirtualImageStorageClassSettings, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VirtualDiskStorageClassSettings_To_componentconfig_VirtualDiskStorageClassSettings(&in.VirtualDiskStorageClassSettings, &out.VirtualDiskStorageClassSettings, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ImportSettings_To_componentconfig_ImportSettings(&in.ImportSettings, &out.ImportSettings, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DVCR_To_componentconfig_DVCR(&in.DVCR, &out.DVCR, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Ingress_To_componentconfig_Ingress(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VirtualizationControllerConfigurationSpec_To_componentconfig_VirtualizationControllerConfigurationSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualizationControllerConfigurationSpec_To_componentconfig_VirtualizationControllerConfigurationSpec(in *VirtualizationControllerConfigurationSpec, out *componentconfig.VirtualizationControllerConfigurationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualizationControllerConfigurationSpec_To_componentconfig_VirtualizationControllerConfigurationSpec(in, out, s)
}

func autoConvert_componentconfig_VirtualizationControllerConfigurationSpec_To_v1alpha1_VirtualizationControllerConfigurationSpec(in *componentconfig.VirtualizationControllerConfigurationSpec, out *VirtualizationControllerConfigurationSpec, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.FirmwareImage = in.FirmwareImage
	out.VirtControllerName = in.VirtControllerName
	out.VirtualMachineCIDRs = *(*[]string)(unsafe.Pointer(&in.VirtualMachineCIDRs))
	out.VirtualMachineIPLeasesRetentionDuration = in.VirtualMachineIPLeasesRetentionDuration
	if err := Convert_componentconfig_GarbageCollector_To_v1alpha1_GarbageCollector(&in.GarbageCollector, &out.GarbageCollector, s); err != nil {
		return err
	}
	if err := Convert_componentconfig_VirtualImageStorageClassSettings_To_v1alpha1_VirtualImageStorageClassSettings(&in.VirtualImageStorageClassSettings, &out.VirtualImageStorageClassSettings, s); err != nil {
		return err
	}
	if err := Convert_componentconfig_VirtualDiskStorageClassSettings_To_v1alpha1_VirtualDiskStorageClassSettings(&in.VirtualDiskStorageClassSettings, &out.VirtualDiskStorageClassSettings, s); err != nil {
		return err
	}
	if err := Convert_componentconfig_ImportSettings_To_v1alpha1_ImportSettings(&in.ImportSettings, &out.ImportSettings, s); err != nil {
		return err
	}
	if err := Convert_componentconfig_DVCR_To_v1alpha1_DVCR(&in.DVCR, &out.DVCR, s); err != nil {
		return err
	}
	if err := Convert_componentconfig_Ingress_To_v1alpha1_Ingress(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_componentconfig_VirtualizationControllerConfigurationSpec_To_v1alpha1_VirtualizationControllerConfigurationSpec is an autogenerated conversion function.
func Convert_componentconfig_VirtualizationControllerConfigurationSpec_To_v1alpha1_VirtualizationControllerConfigurationSpec(in *componentconfig.VirtualizationControllerConfigurationSpec, out *VirtualizationControllerConfigurationSpec, s conversion.Scope) error {
	return autoConvert_componentconfig_VirtualizationControllerConfigurationSpec_To_v1alpha1_VirtualizationControllerConfigurationSpec(in, out, s)
}
