//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseGCSettings) DeepCopyInto(out *BaseGCSettings) {
	*out = *in
	out.TTL = in.TTL
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseGCSettings.
func (in *BaseGCSettings) DeepCopy() *BaseGCSettings {
	if in == nil {
		return nil
	}
	out := new(BaseGCSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DVCR) DeepCopyInto(out *DVCR) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DVCR.
func (in *DVCR) DeepCopy() *DVCR {
	if in == nil {
		return nil
	}
	out := new(DVCR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarbageCollector) DeepCopyInto(out *GarbageCollector) {
	*out = *in
	out.VMOP = in.VMOP
	out.VMIMigration = in.VMIMigration
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarbageCollector.
func (in *GarbageCollector) DeepCopy() *GarbageCollector {
	if in == nil {
		return nil
	}
	out := new(GarbageCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportSettings) DeepCopyInto(out *ImportSettings) {
	*out = *in
	in.Requirements.DeepCopyInto(&out.Requirements)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportSettings.
func (in *ImportSettings) DeepCopy() *ImportSettings {
	if in == nil {
		return nil
	}
	out := new(ImportSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualDiskStorageClassSettings) DeepCopyInto(out *VirtualDiskStorageClassSettings) {
	*out = *in
	if in.AllowedStorageClassNames != nil {
		in, out := &in.AllowedStorageClassNames, &out.AllowedStorageClassNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualDiskStorageClassSettings.
func (in *VirtualDiskStorageClassSettings) DeepCopy() *VirtualDiskStorageClassSettings {
	if in == nil {
		return nil
	}
	out := new(VirtualDiskStorageClassSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualImageStorageClassSettings) DeepCopyInto(out *VirtualImageStorageClassSettings) {
	*out = *in
	if in.AllowedStorageClassNames != nil {
		in, out := &in.AllowedStorageClassNames, &out.AllowedStorageClassNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualImageStorageClassSettings.
func (in *VirtualImageStorageClassSettings) DeepCopy() *VirtualImageStorageClassSettings {
	if in == nil {
		return nil
	}
	out := new(VirtualImageStorageClassSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualizationControllerConfiguration) DeepCopyInto(out *VirtualizationControllerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualizationControllerConfiguration.
func (in *VirtualizationControllerConfiguration) DeepCopy() *VirtualizationControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(VirtualizationControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualizationControllerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualizationControllerConfigurationSpec) DeepCopyInto(out *VirtualizationControllerConfigurationSpec) {
	*out = *in
	if in.VirtualMachineCIDRs != nil {
		in, out := &in.VirtualMachineCIDRs, &out.VirtualMachineCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.VirtualMachineIPLeasesRetentionDuration = in.VirtualMachineIPLeasesRetentionDuration
	out.GarbageCollector = in.GarbageCollector
	in.VirtualImageStorageClassSettings.DeepCopyInto(&out.VirtualImageStorageClassSettings)
	in.VirtualDiskStorageClassSettings.DeepCopyInto(&out.VirtualDiskStorageClassSettings)
	in.ImportSettings.DeepCopyInto(&out.ImportSettings)
	out.DVCR = in.DVCR
	out.Ingress = in.Ingress
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualizationControllerConfigurationSpec.
func (in *VirtualizationControllerConfigurationSpec) DeepCopy() *VirtualizationControllerConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualizationControllerConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}
