FROM golang:1.23-bookworm

RUN apt update -y && apt install -y \
  build-essential \
  libnbd-dev

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

COPY run-fuzz.sh /app/run-fuzz.sh
RUN chmod +x /app/run-fuzz.sh

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=amd64
ENV FUZZ_TIME=2m
ENV GO111MODULE=on

CMD ["/app/run-fuzz.sh"]
