positive:
  configValues:
    - {}
    - virtualMachineCIDRs: ["10.10.10.0/24"]
  values:
    - internal: {}
    - virtualMachineCIDRs: ["10.10.10.0/24"]
      internal: {}
    - https:
        mode: CustomCertificate
        customCertificate:
          secretName: "plainstring"
      internal:
        customCertificateData:
          tls.crt: plainstring
          tls.key: plainstring
negative:
  configValues:
    - virtualMachineCIDRs: []
    - { somethingInConfig: yes }
  values:
    - virtualMachineCIDRs: []
    - { somethingInConfig: yes }
