{{- if and (has "GPU" .Values.virtualization.internal.moduleConfig.featureGates) (semverCompare ">=1.34" .Values.global.discovery.kubernetesVersion) }}
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: gpu.deckhouse.io
  {{- include "helm_lib_module_labels" (list . (dict "app" "virtualization-controller")) | nindent 2 }}
spec:
  selectors:
    - cel:
        expression: 'has(device.attributes["gpu.deckhouse.io"].deviceType)'
{{- end }}
