// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handler

import (
	"context"
	"github.com/deckhouse/virtualization/api/core/v1alpha2"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
	"sync"
)

// Ensure, that CreateOpeartionerMock does implement CreateOpeartioner.
// If this is not the case, regenerate this file with moq.
var _ CreateOpeartioner = &CreateOpeartionerMock{}

// CreateOpeartionerMock is a mock implementation of CreateOpeartioner.
//
//	func TestSomethingThatUsesCreateOpeartioner(t *testing.T) {
//
//		// make and configure a mocked CreateOpeartioner
//		mockedCreateOpeartioner := &CreateOpeartionerMock{
//			ExecuteFunc: func(contextMoqParam context.Context, virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation) (reconcile.Result, error) {
//				panic("mock out the Execute method")
//			},
//			IsCompleteFunc: func(virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation) (bool, string) {
//				panic("mock out the IsComplete method")
//			},
//			IsInProgressFunc: func(virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation) bool {
//				panic("mock out the IsInProgress method")
//			},
//		}
//
//		// use mockedCreateOpeartioner in code that requires CreateOpeartioner
//		// and then make assertions.
//
//	}
type CreateOpeartionerMock struct {
	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(contextMoqParam context.Context, virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation) (reconcile.Result, error)

	// IsCompleteFunc mocks the IsComplete method.
	IsCompleteFunc func(virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation) (bool, string)

	// IsInProgressFunc mocks the IsInProgress method.
	IsInProgressFunc func(virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation) bool

	// calls tracks calls to the methods.
	calls struct {
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// VirtualMachineSnapshotOperation is the virtualMachineSnapshotOperation argument value.
			VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
		}
		// IsComplete holds details about calls to the IsComplete method.
		IsComplete []struct {
			// VirtualMachineSnapshotOperation is the virtualMachineSnapshotOperation argument value.
			VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
		}
		// IsInProgress holds details about calls to the IsInProgress method.
		IsInProgress []struct {
			// VirtualMachineSnapshotOperation is the virtualMachineSnapshotOperation argument value.
			VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
		}
	}
	lockExecute      sync.RWMutex
	lockIsComplete   sync.RWMutex
	lockIsInProgress sync.RWMutex
}

// Execute calls ExecuteFunc.
func (mock *CreateOpeartionerMock) Execute(contextMoqParam context.Context, virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation) (reconcile.Result, error) {
	if mock.ExecuteFunc == nil {
		panic("CreateOpeartionerMock.ExecuteFunc: method is nil but CreateOpeartioner.Execute was just called")
	}
	callInfo := struct {
		ContextMoqParam                 context.Context
		VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
	}{
		ContextMoqParam:                 contextMoqParam,
		VirtualMachineSnapshotOperation: virtualMachineSnapshotOperation,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	return mock.ExecuteFunc(contextMoqParam, virtualMachineSnapshotOperation)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//
//	len(mockedCreateOpeartioner.ExecuteCalls())
func (mock *CreateOpeartionerMock) ExecuteCalls() []struct {
	ContextMoqParam                 context.Context
	VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
} {
	var calls []struct {
		ContextMoqParam                 context.Context
		VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}

// IsComplete calls IsCompleteFunc.
func (mock *CreateOpeartionerMock) IsComplete(virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation) (bool, string) {
	if mock.IsCompleteFunc == nil {
		panic("CreateOpeartionerMock.IsCompleteFunc: method is nil but CreateOpeartioner.IsComplete was just called")
	}
	callInfo := struct {
		VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
	}{
		VirtualMachineSnapshotOperation: virtualMachineSnapshotOperation,
	}
	mock.lockIsComplete.Lock()
	mock.calls.IsComplete = append(mock.calls.IsComplete, callInfo)
	mock.lockIsComplete.Unlock()
	return mock.IsCompleteFunc(virtualMachineSnapshotOperation)
}

// IsCompleteCalls gets all the calls that were made to IsComplete.
// Check the length with:
//
//	len(mockedCreateOpeartioner.IsCompleteCalls())
func (mock *CreateOpeartionerMock) IsCompleteCalls() []struct {
	VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
} {
	var calls []struct {
		VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
	}
	mock.lockIsComplete.RLock()
	calls = mock.calls.IsComplete
	mock.lockIsComplete.RUnlock()
	return calls
}

// IsInProgress calls IsInProgressFunc.
func (mock *CreateOpeartionerMock) IsInProgress(virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation) bool {
	if mock.IsInProgressFunc == nil {
		panic("CreateOpeartionerMock.IsInProgressFunc: method is nil but CreateOpeartioner.IsInProgress was just called")
	}
	callInfo := struct {
		VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
	}{
		VirtualMachineSnapshotOperation: virtualMachineSnapshotOperation,
	}
	mock.lockIsInProgress.Lock()
	mock.calls.IsInProgress = append(mock.calls.IsInProgress, callInfo)
	mock.lockIsInProgress.Unlock()
	return mock.IsInProgressFunc(virtualMachineSnapshotOperation)
}

// IsInProgressCalls gets all the calls that were made to IsInProgress.
// Check the length with:
//
//	len(mockedCreateOpeartioner.IsInProgressCalls())
func (mock *CreateOpeartionerMock) IsInProgressCalls() []struct {
	VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
} {
	var calls []struct {
		VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
	}
	mock.lockIsInProgress.RLock()
	calls = mock.calls.IsInProgress
	mock.lockIsInProgress.RUnlock()
	return calls
}
