// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handler

import (
	"context"
	"github.com/deckhouse/virtualization-controller/pkg/controller/service/restorer"
	"github.com/deckhouse/virtualization/api/core/v1alpha2"
	"sync"
)

// Ensure, that CreateOperationExecutorMock does implement CreateOperationExecutor.
// If this is not the case, regenerate this file with moq.
var _ CreateOperationExecutor = &CreateOperationExecutorMock{}

// CreateOperationExecutorMock is a mock implementation of CreateOperationExecutor.
//
//	func TestSomethingThatUsesCreateOperationExecutor(t *testing.T) {
//
//		// make and configure a mocked CreateOperationExecutor
//		mockedCreateOperationExecutor := &CreateOperationExecutorMock{
//			ExecuteFunc: func(contextMoqParam context.Context, virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation, virtualMachineSnapshot *v1alpha2.VirtualMachineSnapshot, manifestReader restorer.ManifestReader) error {
//				panic("mock out the Execute method")
//			},
//		}
//
//		// use mockedCreateOperationExecutor in code that requires CreateOperationExecutor
//		// and then make assertions.
//
//	}
type CreateOperationExecutorMock struct {
	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(contextMoqParam context.Context, virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation, virtualMachineSnapshot *v1alpha2.VirtualMachineSnapshot, manifestReader restorer.ManifestReader) error

	// calls tracks calls to the methods.
	calls struct {
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// VirtualMachineSnapshotOperation is the virtualMachineSnapshotOperation argument value.
			VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
			// VirtualMachineSnapshot is the virtualMachineSnapshot argument value.
			VirtualMachineSnapshot *v1alpha2.VirtualMachineSnapshot
			// ManifestReader is the manifestReader argument value.
			ManifestReader restorer.ManifestReader
		}
	}
	lockExecute sync.RWMutex
}

// Execute calls ExecuteFunc.
func (mock *CreateOperationExecutorMock) Execute(contextMoqParam context.Context, virtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation, virtualMachineSnapshot *v1alpha2.VirtualMachineSnapshot, manifestReader restorer.ManifestReader) error {
	if mock.ExecuteFunc == nil {
		panic("CreateOperationExecutorMock.ExecuteFunc: method is nil but CreateOperationExecutor.Execute was just called")
	}
	callInfo := struct {
		ContextMoqParam                 context.Context
		VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
		VirtualMachineSnapshot          *v1alpha2.VirtualMachineSnapshot
		ManifestReader                  restorer.ManifestReader
	}{
		ContextMoqParam:                 contextMoqParam,
		VirtualMachineSnapshotOperation: virtualMachineSnapshotOperation,
		VirtualMachineSnapshot:          virtualMachineSnapshot,
		ManifestReader:                  manifestReader,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	return mock.ExecuteFunc(contextMoqParam, virtualMachineSnapshotOperation, virtualMachineSnapshot, manifestReader)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//
//	len(mockedCreateOperationExecutor.ExecuteCalls())
func (mock *CreateOperationExecutorMock) ExecuteCalls() []struct {
	ContextMoqParam                 context.Context
	VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
	VirtualMachineSnapshot          *v1alpha2.VirtualMachineSnapshot
	ManifestReader                  restorer.ManifestReader
} {
	var calls []struct {
		ContextMoqParam                 context.Context
		VirtualMachineSnapshotOperation *v1alpha2.VirtualMachineSnapshotOperation
		VirtualMachineSnapshot          *v1alpha2.VirtualMachineSnapshot
		ManifestReader                  restorer.ManifestReader
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}
