{
 "title": "Namespace / Virtual Machines",
 "tags": [ "main" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_status_phase,namespace)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_network_receive_bytes_total{namespace=~\"$namespace\"},network)"
    }
   },
   {
    "name": "mount_point",
    "label": "Mountpoint",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_filesystem_capacity_bytes{namespace=\"$namespace\", name=\"$name\"},mount_point)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kubernetes_build_info,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VM statuses",
   "type": "bargauge",
   "description": "Shows the number of virtual machines by lifecycle phases \n\n* `Pending` - VM awaits resources (e.g., disks, IP addresses) after creation or restart.\n* `Starting` - VM attempts to start on a cluster node with resources ready.\n* `Running` - VM is operational, running on a node.\n* `Stopping` - VM is being stopped or rebooted.\n* `Stopped` - VM is inactive, using no computational resources.\n* `Terminating` - VM is being deleted, releasing resources.\n* `Migrating` - VM is live-migrated to another node, requiring non-local disks.\n",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (d8_virtualization_virtualmachine_status_phase{namespace=~\"$namespace\"}==1)",
     "legendFormat": "Total VM count"
    },
    {
     "expr": "count by (phase) (d8_virtualization_virtualmachine_status_phase{namespace=~\"$namespace\"}==1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count (d8_virtualization_virtualmachine_agent_ready{namespace=~\"$namespace\"}==1) or vector(0)",
     "legendFormat": "Agent ready"
    }
   ]
  },
  {
   "title": "Disk statuses",
   "type": "bargauge",
   "description": "Shows the number of virtual disk by lifecycle phases\n- `Pending` - waiting for all dependent resources required for disk creation to be ready.\n- `Provisioning` - disk creation process is in progress.\n- `Resizing` - the process of resizing the disk is in progress.\n- `WaitForFirstConsumer` - the disk is waiting for the virtual machine that will use it to be created.\n- `WaitForUserUpload` - the disk is waiting for the user to upload an image (type: Upload).\n- `Ready` - the disk has been created and is ready for use.\n- `Failed` - an error occurred during the creation process.\n- `PVCLost` - system error, PVC with data has been lost.\n- `Terminating` - the disk is being deleted. The disk may \"hang\" in this state if it is still connected to the virtual machine.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (d8_virtualization_virtualdisk_status_phase{namespace=~\"$namespace\"}==1)",
     "legendFormat": "Total disk count"
    },
    {
     "expr": "count by (phase) (d8_virtualization_virtualdisk_status_phase{namespace=~\"$namespace\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quota usage",
   "type": "gauge",
   "description": "Displays resource quota usage (CPU, Memory, Storage) as percentage of available limits. Requires resource quotas to be configured in the namespace.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(  \n    (sum(kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.cpu\", type=\"used\"}))\n)\n/\n( \n    (sum(kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.cpu\", type=\"hard\"}) / 100)\n) or vector(0)",
     "legendFormat": "CPU",
     "nullValueMode": "null"
    },
    {
     "expr": "(  \n    sum(kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.memory\", type=\"used\"})\n)\n/\n( \n    (sum(kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.memory\", type=\"hard\"}) / 100)\n) or vector(0)",
     "legendFormat": "Memory",
     "nullValueMode": "null"
    },
    {
     "expr": "(\n    sum(kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.storage\", type=\"used\"})\n)\n/\n(\n    (sum(kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.storage\", type=\"hard\"}) / 100)\n) or vector(0)",
     "legendFormat": "Storage",
     "nullValueMode": "null"
    }
   ]
  },
  {
   "title": "Quota allocation",
   "type": "stat",
   "description": "Shows the total allocated resources from resource quotas:\n\n* `CPU Cores` - total CPU cores allocated\n* `Memory` - total memory allocated\n* `Storage` - total storage allocated",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nkube_resourcequota{namespace=~\"$namespace\", resource=\"requests.cpu\", type=\"used\"}\n)\n",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "sum (\nkube_resourcequota{namespace=~\"$namespace\", resource=\"requests.memory\", type=\"used\"}\n)\n",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum (\nkube_resourcequota{namespace=~\"$namespace\", resource=\"requests.storage\", type=\"used\"}\n)\n",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Other resources",
   "type": "stat",
   "description": "Shows the count of additional virtualization resources:\n\n* `VirtualImages` - number of virtual images\n* `VirtualDiskSnapshots` - number of disk snapshots\n* `VirtualMachineSnapshots` - number of virtual machine snapshots",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nd8_virtualization_virtualimage_status_phase{namespace=~\"$namespace\"}==1\n) or vector(0)\n",
     "legendFormat": "VirtualImages"
    },
    {
     "expr": "sum (\nd8_virtualization_virtualdisksnapshot_status_phase{namespace=~\"$namespace\"}==1\n) or vector(0)\n",
     "legendFormat": "VirtualDiskSnapshots"
    },
    {
     "expr": "sum (\nd8_virtualization_virtualmachinesnapshot_status_phase{namespace=~\"$namespace\"}==1\n) or vector(0)\n",
     "legendFormat": "VirtualMachineSnapshots"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "stat",
   "description": "Shows the total resource quota limits configured for the namespace:\n\n* `CPU Cores` - maximum CPU cores allowed\n* `Memory` - maximum memory allowed\n* `Storage` - maximum storage allowed",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nkube_resourcequota{namespace=~\"$namespace\", resource=\"requests.cpu\", type=\"hard\"}\n) or vector(0)\n",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "sum (\nkube_resourcequota{namespace=~\"$namespace\", resource=\"requests.memory\", type=\"hard\"}\n) or vector(0)\n",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum (\nkube_resourcequota{namespace=~\"$namespace\", resource=\"requests.storage\", type=\"hard\"}\n) \n",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "VM Usage",
   "type": "stat",
   "description": "Shows the actual resource usage by virtual machines:\n\n* `CPU Cores` - current CPU usage by VMs\n* `Memory` - current memory usage by VMs\n* `Storage` - current storage usage by VMs",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(d8_virtualization_virtualmachine_cpu_usage_milliseconds_total{namespace=~\"$namespace\"}[$__rate_interval])) / 1000",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "sum by (namespace) (d8_virtualization_virtualmachine_os_memory_total_bytes - d8_virtualization_virtualmachine_os_memory_potentially_free_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum (\nkube_resourcequota{namespace=~\"$namespace\", resource=\"requests.storage\", type=\"used\"}\n) or sum(d8_virtualization_virtualdisk_capacity_bytes{namespace=~\"$namespace\"})\n",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Virtual machines",
   "type": "table",
   "description": "Detailed table of all virtual machines with status information, resources and links to detailed dashboards\n\n* `Pending` - VM awaits resources (e.g., disks, IP addresses) after creation or restart.\n* `Starting` - VM attempts to start on a cluster node with resources ready.\n* `Running` - VM is operational, running on a node.\n* `Stopping` - VM is being stopped or rebooted.\n* `Stopped` - VM is inactive, using no computational resources.\n* `Terminating` - VM is being deleted, releasing resources.\n* `Migrating` - VM is live-migrated to another node, requiring non-local disks.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (namespace, name, phase) (d8_virtualization_virtualmachine_status_phase{namespace=~\"$namespace\"})==1",
     "legendFormat": "Virtual Machine"
    },
    {
     "expr": "max by (namespace, name, phase) (d8_virtualization_virtualmachine_agent_ready{namespace=~\"$namespace\"})",
     "legendFormat": "Agent"
    },
    {
     "expr": "avg by (namespace, name) (rate(d8_virtualization_virtualmachine_cpu_usage_milliseconds_total{namespace=~\"$namespace\"}[$__rate_interval])) / 1000",
     "legendFormat": "OS Usage"
    },
    {
     "expr": "sum by (namespace, name) (d8_virtualization_virtualmachine_cpu_cores{namespace=~\"$namespace\"})",
     "legendFormat": "Current CPU cores"
    },
    {
     "expr": "avg by (namespace, name) ((d8_virtualization_virtualmachine_cpu_cores{namespace=~\"$namespace\"} * d8_virtualization_virtualmachine_cpu_core_fraction) / 100)",
     "legendFormat": "Guaranteed CPU cores"
    },
    {
     "expr": "avg by (namespace, name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "Memory current"
    },
    {
     "expr": "avg by (namespace, name) (d8_virtualization_virtualmachine_configuration_memory_size_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "Memory configured"
    },
    {
     "expr": "avg by (namespace, name) (d8_virtualization_virtualmachine_os_memory_total_bytes - d8_virtualization_virtualmachine_os_memory_potentially_free_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "Read IOPs"
    },
    {
     "expr": "avg by (namespace, name) (rate(d8_virtualization_virtualmachine_block_device_iops_read_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval]))",
     "legendFormat": "Read IOPs"
    },
    {
     "expr": "avg by (namespace, name) (rate(d8_virtualization_virtualmachine_block_device_iops_write_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (namespace, name) (rate(d8_virtualization_virtualmachine_network_receive_bytes_total{namespace=~\"$namespace\"}[$__rate_interval])*8)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (namespace, name) (rate(d8_virtualization_virtualmachine_network_transmit_bytes_total{namespace=~\"$namespace\"}[$__rate_interval])*8)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (namespace, name) (\n    label_replace(\n        d8_virtualization_virtualdisk_status_in_use{namespace=~\"$namespace\"}, \n        \"name\", \n        \"$1\", \n        \"virtualmachine\", \n        \"(.+)\"\n    )\n) * on(namespace, name) group_left() (\n    d8_virtualization_virtualmachine_status_phase{namespace=~\"$namespace\"} == 1\n)",
     "legendFormat": "Disks attached"
    },
    {
     "expr": "count by (namespace, name) (\n    label_replace(\n        d8_virtualization_virtualmachinesnapshot_info{namespace=~\"$namespace\"}, \n        \"name\", \n        \"$1\", \n        \"virtualmachine\", \n        \"(.+)\"\n    )\n) * on(namespace, name) group_left() (\n    d8_virtualization_virtualmachine_status_phase{namespace=~\"$namespace\"} == 1\n)",
     "legendFormat": "Snapshots"
    }
   ]
  },
  {
   "title": "VM status details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM status timeline",
     "type": "state-timeline",
     "description": "Timeline of virtual machine status changes for tracking their lifecycle\n\n**VM Phases:**\n* `Pending` - VM awaits resources (e.g., disks, IP addresses) after creation or restart\n* `Starting` - VM attempts to start on a cluster node with resources ready\n* `Running` - VM is operational, running on a node\n* `Stopping` - VM is being stopped or rebooted\n* `Stopped` - VM is inactive, using no computational resources\n* `Terminating` - VM is being deleted, releasing resources\n* `Migrating` - VM is live-migrated to another node, requiring non-local disks\n* `Degraded` - VM is in a degraded state\n* `Pause` - VM is paused",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "sum by (name,namespace) ((d8_virtualization_virtualmachine_status_phase{namespace=~\"$namespace\"} == 1) * on(phase) group_left()\n    (\n      label_replace(vector(1), \"phase\", \"Degraded\", \"\", \"\") or\n      label_replace(vector(2), \"phase\", \"Migrating\", \"\", \"\") or\n      label_replace(vector(3), \"phase\", \"Pause\", \"\", \"\") or\n      label_replace(vector(4), \"phase\", \"Pending\", \"\", \"\") or\n      label_replace(vector(5), \"phase\", \"Running\", \"\", \"\") or\n      label_replace(vector(6), \"phase\", \"Starting\", \"\", \"\") or\n      label_replace(vector(7), \"phase\", \"Stopped\", \"\", \"\") or\n      label_replace(vector(8), \"phase\", \"Stopping\", \"\", \"\") or\n      label_replace(vector(9), \"phase\", \"Terminating\", \"\", \"\")\n    ))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores total",
     "type": "timeseries",
     "description": "Chart showing changes in total CPU cores over time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(d8_virtualization_virtualmachine_cpu_usage_milliseconds_total{namespace=~\"$namespace\"}[$__rate_interval])) / 1000",
       "legendFormat": "OS Usage / {{ name }} "
      },
      {
       "expr": "sum (rate(d8_virtualization_virtualmachine_hypervisor_cpu_usage_milliseconds_total{namespace=~\"$namespace\"}[$__rate_interval])) / 1000\n",
       "legendFormat": "Hypervisor overhead"
      },
      {
       "expr": "sum ((d8_virtualization_virtualmachine_cpu_cores{namespace=~\"$namespace\"} * d8_virtualization_virtualmachine_cpu_core_fraction) / 100)\n",
       "legendFormat": "Guaranteed cores"
      },
      {
       "expr": "sum (d8_virtualization_virtualmachine_cpu_cores{namespace=~\"$namespace\"})\n",
       "legendFormat": "Current cores"
      },
      {
       "expr": "sum (rate(d8_virtualization_virtualmachine_cpu_steal_milliseconds_total{namespace=~\"$namespace\"}[$__rate_interval])) / 1000",
       "legendFormat": "Steal cores"
      },
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.cpu\", type=\"hard\"}",
       "legendFormat": "Quota"
      },
      {
       "expr": "sum (rate(d8_virtualization_virtualmachine_cpu_usage_milliseconds_total{namespace=~\"$namespace\"}[$__rate_interval])) / 1000",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage total",
     "type": "timeseries",
     "description": "Chart showing changes in total memory usage by virtual machines over time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (d8_virtualization_virtualmachine_memory_size_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "Configured memory"
      },
      {
       "expr": "sum by (name) (d8_virtualization_virtualmachine_os_memory_total_bytes - d8_virtualization_virtualmachine_os_memory_potentially_free_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "OS Usage / {{ name }} "
      },
      {
       "expr": "sum (d8_virtualization_virtualmachine_os_memory_total_bytes{namespace=~\"$namespace\"})\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum (d8_virtualization_virtualmachine_configuration_memory_runtime_overhead_bytes{namespace=~\"$namespace\"})\n",
       "legendFormat": "Hypervisor Memory Overhead"
      },
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.memory\", type=\"hard\"}",
       "legendFormat": "Quota"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual disks",
     "type": "table",
     "description": "Detailed table of all virtual disk with status information\n\n- `Pending` - waiting for all dependent resources required for disk creation to be ready.\n- `Provisioning` - disk creation process is in progress.\n- `Resizing` - the process of resizing the disk is in progress.\n- `WaitForFirstConsumer` - the disk is waiting for the virtual machine that will use it to be created.\n- `WaitForUserUpload` - the disk is waiting for the user to upload an image (type: Upload).\n- `Ready` - the disk has been created and is ready for use.\n- `Failed` - an error occurred during the creation process.\n- `PVCLost` - system error, PVC with data has been lost.\n- `Terminating` - the disk is being deleted. The disk may \"hang\" in this state if it is still connected to the virtual machine.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (namespace, name, phase) (d8_virtualization_virtualdisk_status_phase{namespace=~\"$namespace\"})==1",
       "legendFormat": "Virtual Machine"
      },
      {
       "expr": "max by (namespace, name, virtualmachine) (d8_virtualization_virtualdisk_status_in_use{namespace=~\"$namespace\"})",
       "legendFormat": "Virtual Machine"
      },
      {
       "expr": "max by (namespace, name) (d8_virtualization_virtualdisk_capacity_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "Virtual Machine"
      },
      {
       "expr": "count by (namespace, name) (\n    label_replace(\n        d8_virtualization_virtualdisksnapshot_info{namespace=~\"$namespace\"}, \n        \"name\", \n        \"$1\", \n        \"virtualdisk\", \n        \"(.+)\"\n    )\n) * on(namespace, name) group_left() (\n    d8_virtualization_virtualdisk_status_phase{namespace=~\"$namespace\"} == 1\n)",
       "legendFormat": "Virtual Machine"
      },
      {
       "expr": "max by (namespace, name, storageclass) (d8_virtualization_virtualdisk_info{namespace=~\"$namespace\"})",
       "legendFormat": "Virtual Machine"
      }
     ]
    },
    {
     "title": "Storage usage total",
     "type": "timeseries",
     "description": "Chart showing changes in total storage usage by virtual machines over time with quota limits. Requires qemu-guest-agent to be installed in VMs.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "d8_virtualization_virtualdisk_capacity_bytes{namespace=~\"$namespace\"}",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.storage\", type=\"hard\"}",
       "legendFormat": "Quota"
      }
     ]
    },
    {
     "title": "File systems usage total",
     "type": "timeseries",
     "description": "Chart showing changes in total filesystem usage by virtual machines over time. Requires qemu-guest-agent to be installed in VMs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "repeat": "mount_point",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (d8_virtualization_virtualmachine_filesystem_capacity_bytes{namespace=~\"$namespace\", type!=\"cloudinit\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum (d8_virtualization_virtualmachine_filesystem_used_bytes{namespace=~\"$namespace\", type!=\"cloudinit\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "FS usage per VM",
     "type": "timeseries",
     "description": "Chart showing filesystem usage for each virtual machine separately. Requires qemu-guest-agent to be installed in VMs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (namespace, name) (d8_virtualization_virtualmachine_filesystem_used_bytes{namespace=~\"$namespace\", type!=\"cloudinit\"})",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage I/O details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read IOPS per VM",
     "type": "timeseries",
     "description": "Chart showing number of disk read operations per second for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (namespace, name) (rate(d8_virtualization_virtualmachine_block_device_iops_read_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Disk write IOPS per VM",
     "type": "timeseries",
     "description": "Chart showing number of disk write operations per second for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (namespace, name) (rate(d8_virtualization_virtualmachine_block_device_iops_write_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Disk read latency per VM",
     "type": "timeseries",
     "description": "Chart showing disk read operation latency for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (namespace, name) (\n    rate(d8_virtualization_virtualmachine_block_device_read_times_seconds_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval])\n    /\n    clamp_min(rate(d8_virtualization_virtualmachine_block_device_iops_read_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval]), 0.0001)\n) * 1000",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Disk write latency per VM",
     "type": "timeseries",
     "description": "Chart showing disk write operation latency for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (namespace, name) (\n    rate(d8_virtualization_virtualmachine_block_device_write_times_seconds_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval])\n    /\n    clamp_min(rate(d8_virtualization_virtualmachine_block_device_iops_write_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval]), 0.0001)\n    )",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Disk read throughput per VM",
     "type": "timeseries",
     "description": "Chart showing disk read throughput for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (namespace, name) (rate(d8_virtualization_virtualmachine_block_device_read_traffic_bytes_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Disk write throughput per VM",
     "type": "timeseries",
     "description": "Chart showing disk write throughput for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (namespace, name) (rate(d8_virtualization_virtualmachine_block_device_write_traffic_bytes_total{namespace=~\"$namespace\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network \"$network\" details ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "network",
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth usage per VM - $network",
     "type": "timeseries",
     "description": "Chart showing network bandwidth usage for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (network, namespace, name) (rate(d8_virtualization_virtualmachine_network_receive_bytes_total{namespace=~\"$namespace\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX bps {{ name }}"
      },
      {
       "expr": "sum by (network, namespace, name) (rate(d8_virtualization_virtualmachine_network_transmit_bytes_total{namespace=~\"$namespace\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX bps {{ name }}"
      }
     ]
    },
    {
     "title": "Packet rate per VM - $network",
     "type": "timeseries",
     "description": "Chart showing packet transmission rate for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (network, namespace, name) (rate(d8_virtualization_virtualmachine_network_receive_packets_total{namespace=~\"$namespace\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX pps",
       "nullValueMode": "null"
      },
      {
       "expr": "sum by (network, namespace, name) (rate(d8_virtualization_virtualmachine_network_transmit_packets_total{namespace=~\"$namespace\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX pps",
       "nullValueMode": "null"
      }
     ]
    },
    {
     "title": "Packet drops per VM - $network",
     "type": "timeseries",
     "description": "Chart showing number of dropped packets for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg by (network, namespace, name) (rate(d8_virtualization_virtualmachine_network_receive_packets_dropped_total{namespace=~\"$namespace\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX {{ name }}",
       "nullValueMode": "null"
      },
      {
       "expr": "avg by (network, namespace, name) (rate(d8_virtualization_virtualmachine_network_transmit_packets_dropped_total{namespace=~\"$namespace\",  network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX {{ name }}",
       "nullValueMode": "null"
      }
     ]
    },
    {
     "title": "Interface errors per VM - $network",
     "type": "timeseries",
     "description": "Chart showing number of network interface errors for each virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (network, namespace, name) (rate(d8_virtualization_virtualmachine_network_receive_errors_total{namespace=~\"$namespace\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX {{ name }}",
       "nullValueMode": "null"
      },
      {
       "expr": "sum by (network, namespace, name) (rate(d8_virtualization_virtualmachine_network_transmit_errors_total{namespace=~\"$namespace\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX {{ name }}",
       "nullValueMode": "null"
      }
     ]
    }
   ]
  }
 ]
}