#!/usr/bin/env bash
# Copyright 2026 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# shellcheck disable=SC2154 # CI_* and GITLAB_API_TOKEN are injected by the GitLab Runner at job runtime.

# Backport a merged MR to a release branch by opening a backport MR.
#
# Migration of .github/workflows/on-pull-request-backport.yml which used
# deckhouse/backport-action@v1.0.0 and direct cherry-pick to release branch.
#
# Per migration plan §0(6) and §11.9 we DO NOT use the GitLab cherry-pick
# REST endpoint (POST /repository/commits/:sha/cherry_pick) because it
# bypasses code review. Instead we:
#   1. clone the repo (or reuse the runner workspace),
#   2. cherry-pick the merged commit (or head SHA),
#   3. push a backport branch,
#   4. open an MR to the target release branch via push options / API.
#
# Required environment:
#   GITLAB_API_TOKEN, CI_API_V4_URL, CI_PROJECT_ID, CI_SERVER_HOST,
#   CI_PROJECT_PATH, TARGET_BRANCH (e.g. release-1.21)
#   SOURCE_MR_IID (optional; defaults to CI_MERGE_REQUEST_IID)
#
# Optional environment:
#   CI_MERGE_REQUEST_LABELS — used to detect a backport-release-X.Y label
#     if TARGET_BRANCH is not provided explicitly (manual pipeline UI fallback).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=.gitlab/ci/scripts/bash/lib/api.sh
source "${SCRIPT_DIR}/lib/api.sh"

gl_required_env CI_API_V4_URL GITLAB_API_TOKEN CI_PROJECT_ID CI_SERVER_HOST CI_PROJECT_PATH

# Determine TARGET_BRANCH (priority: explicit var > label-based inference).
TARGET_BRANCH="${TARGET_BRANCH:-}"
if [[ -z "$TARGET_BRANCH" ]]; then
  if [[ "${CI_MERGE_REQUEST_LABELS:-}" =~ backport-release-([0-9]+\.[0-9]+) ]]; then
    TARGET_BRANCH="release-${BASH_REMATCH[1]}"
  fi
fi

if [[ -z "$TARGET_BRANCH" ]]; then
  echo "ERROR: TARGET_BRANCH is required (e.g. release-1.21)." >&2
  echo "Set it via 'Run pipeline' UI, or add a backport-release-X.Y label to the MR." >&2
  exit 1
fi
if ! [[ "$TARGET_BRANCH" =~ ^release-[0-9]+\.[0-9]+$ ]]; then
  echo "ERROR: TARGET_BRANCH='${TARGET_BRANCH}' does not match ^release-[0-9]+\.[0-9]+\$" >&2
  exit 1
fi

SOURCE_MR_IID="${SOURCE_MR_IID:-${CI_MERGE_REQUEST_IID:-}}"
if [[ -z "$SOURCE_MR_IID" ]]; then
  echo "ERROR: SOURCE_MR_IID is required (CI_MERGE_REQUEST_IID unset and no explicit var)." >&2
  exit 1
fi

echo "Backport target: ${TARGET_BRANCH}"
echo "Source MR: !${SOURCE_MR_IID}"

# 1) Read source MR to get the merged commit SHA.
mr_path="/projects/${CI_PROJECT_ID}/merge_requests/${SOURCE_MR_IID}"
mr_json="$(api GET "${mr_path}")"
sha="$(printf '%s' "$mr_json" | jq -r '.merge_commit_sha // .sha // empty')"
if [[ -z "$sha" || "$sha" == "null" ]]; then
  echo "ERROR: could not extract SHA from MR !${SOURCE_MR_IID} (not merged yet?)." >&2
  exit 1
fi
echo "Source commit SHA: ${sha}"

# 2) Verify target branch exists (gives a clearer error than a git fetch failure).
if ! api GET "/projects/${CI_PROJECT_ID}/repository/branches/${TARGET_BRANCH}" >/dev/null; then
  echo "ERROR: target branch '${TARGET_BRANCH}' does not exist in this project." >&2
  exit 1
fi

# 3) Use the runner workspace (GitLab already cloned the repo here).
cd "${CI_PROJECT_DIR:?CI_PROJECT_DIR is required}"

git config user.email "ci-backport@flant.com"
git config user.name  "GitLab CI Backport Bot"

REPO_URL="https://oauth2:${GITLAB_API_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
git remote set-url origin "${REPO_URL}"

# Fetch the target branch.
git fetch --no-tags --depth=200 origin "${TARGET_BRANCH}"

BACKPORT_BRANCH="backport/${SOURCE_MR_IID}/${TARGET_BRANCH}"
echo "Creating backport branch: ${BACKPORT_BRANCH}"
git checkout -B "${BACKPORT_BRANCH}" "origin/${TARGET_BRANCH}"

CONFLICT_MARKER=""
# 4) Cherry-pick. GIT_SEQUENCE_EDITOR=/dev/null drops the default commit message
#    editor so the script can run unattended.
GIT_SEQUENCE_EDITOR=true git cherry-pick -x "${sha}" || {
  CONFLICT_MARKER="
**Conflicts detected** — please resolve manually, amend the commit, and force-push.
"
  echo "Cherry-pick reported conflicts; staging resolved tree as best-effort commit."
  # Best-effort: keep partial progress so reviewer can see what was applied.
  git add -A || true
  if ! git diff --cached --quiet; then
    git -c core.editor=true commit --no-edit || true
  fi
}

# 5) Push with push options to create MR in one step.
DESCRIPTION="Backport !${SOURCE_MR_IID} (${sha}) to ${TARGET_BRANCH}.

Auto-generated by GitLab CI backport job.
${CONFLICT_MARKER}"

# Build payload for a single API call to create MR after push, because push
# options are limited and we want fine-grained control of body/labels.
push_output="$(git push --force-with-lease \
  -o merge_request.create \
  -o merge_request.target="${TARGET_BRANCH}" \
  -o merge_request.source="${BACKPORT_BRANCH}" \
  -o merge_request.title="Backport !${SOURCE_MR_IID} to ${TARGET_BRANCH}" \
  -o merge_request.description="${DESCRIPTION}" \
  -o merge_request.label="backport" \
  -o merge_request.label="auto" \
  -o merge_request.remove_source_branch \
  origin "${BACKPORT_BRANCH}" 2>&1 || true)"
echo "${push_output}"

# 6) As a fallback (push options ignored on some GitLab versions), explicitly
#    POST the MR via API if push did not create one. We search for an open MR
#    from our branch first; if absent, we create it.
existing_mr_iid="$(api GET "/projects/${CI_PROJECT_ID}/merge_requests?source_branch=${BACKPORT_BRANCH}&state=opened" \
  | jq -r 'if type == "array" and length > 0 then .[0].iid else empty end')"

if [[ -z "$existing_mr_iid" ]]; then
  echo "Push options did not create MR; creating via API..."
  payload="$(jq -n \
    --arg src "${BACKPORT_BRANCH}" \
    --arg tgt "${TARGET_BRANCH}" \
    --arg title "Backport !${SOURCE_MR_IID} to ${TARGET_BRANCH}" \
    --arg desc "${DESCRIPTION}" \
    '{source_branch: $src, target_branch: $tgt, title: $title, description: $desc, remove_source_branch: true, labels: "backport,auto"}')"
  api POST "/projects/${CI_PROJECT_ID}/merge_requests" --data "${payload}" \
    | jq -r '"Created MR !\(.iid) at \(.web_url)"'
else
  echo "Backport MR already exists: !${existing_mr_iid}"
fi
