// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package volumemode

import (
	"context"
	corev1 "k8s.io/api/core/v1"
	storagev1 "k8s.io/api/storage/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sync"
)

// Ensure, that VolumeAndAccessModesGetterMock does implement VolumeAndAccessModesGetter.
// If this is not the case, regenerate this file with moq.
var _ VolumeAndAccessModesGetter = &VolumeAndAccessModesGetterMock{}

// VolumeAndAccessModesGetterMock is a mock implementation of VolumeAndAccessModesGetter.
//
//	func TestSomethingThatUsesVolumeAndAccessModesGetter(t *testing.T) {
//
//		// make and configure a mocked VolumeAndAccessModesGetter
//		mockedVolumeAndAccessModesGetter := &VolumeAndAccessModesGetterMock{
//			GetVolumeAndAccessModesFunc: func(ctx context.Context, obj client.Object, sc *storagev1.StorageClass) (corev1.PersistentVolumeMode, corev1.PersistentVolumeAccessMode, error) {
//				panic("mock out the GetVolumeAndAccessModes method")
//			},
//		}
//
//		// use mockedVolumeAndAccessModesGetter in code that requires VolumeAndAccessModesGetter
//		// and then make assertions.
//
//	}
type VolumeAndAccessModesGetterMock struct {
	// GetVolumeAndAccessModesFunc mocks the GetVolumeAndAccessModes method.
	GetVolumeAndAccessModesFunc func(ctx context.Context, obj client.Object, sc *storagev1.StorageClass) (corev1.PersistentVolumeMode, corev1.PersistentVolumeAccessMode, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetVolumeAndAccessModes holds details about calls to the GetVolumeAndAccessModes method.
		GetVolumeAndAccessModes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Obj is the obj argument value.
			Obj client.Object
			// Sc is the sc argument value.
			Sc *storagev1.StorageClass
		}
	}
	lockGetVolumeAndAccessModes sync.RWMutex
}

// GetVolumeAndAccessModes calls GetVolumeAndAccessModesFunc.
func (mock *VolumeAndAccessModesGetterMock) GetVolumeAndAccessModes(ctx context.Context, obj client.Object, sc *storagev1.StorageClass) (corev1.PersistentVolumeMode, corev1.PersistentVolumeAccessMode, error) {
	if mock.GetVolumeAndAccessModesFunc == nil {
		panic("VolumeAndAccessModesGetterMock.GetVolumeAndAccessModesFunc: method is nil but VolumeAndAccessModesGetter.GetVolumeAndAccessModes was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Obj client.Object
		Sc  *storagev1.StorageClass
	}{
		Ctx: ctx,
		Obj: obj,
		Sc:  sc,
	}
	mock.lockGetVolumeAndAccessModes.Lock()
	mock.calls.GetVolumeAndAccessModes = append(mock.calls.GetVolumeAndAccessModes, callInfo)
	mock.lockGetVolumeAndAccessModes.Unlock()
	return mock.GetVolumeAndAccessModesFunc(ctx, obj, sc)
}

// GetVolumeAndAccessModesCalls gets all the calls that were made to GetVolumeAndAccessModes.
// Check the length with:
//
//	len(mockedVolumeAndAccessModesGetter.GetVolumeAndAccessModesCalls())
func (mock *VolumeAndAccessModesGetterMock) GetVolumeAndAccessModesCalls() []struct {
	Ctx context.Context
	Obj client.Object
	Sc  *storagev1.StorageClass
} {
	var calls []struct {
		Ctx context.Context
		Obj client.Object
		Sc  *storagev1.StorageClass
	}
	mock.lockGetVolumeAndAccessModes.RLock()
	calls = mock.calls.GetVolumeAndAccessModes
	mock.lockGetVolumeAndAccessModes.RUnlock()
	return calls
}
