// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dvcr

import (
	"context"
	"sync"
)

// Ensure, that ImageCheckerMock does implement ImageChecker.
// If this is not the case, regenerate this file with moq.
var _ ImageChecker = &ImageCheckerMock{}

// ImageCheckerMock is a mock implementation of ImageChecker.
//
//	func TestSomethingThatUsesImageChecker(t *testing.T) {
//
//		// make and configure a mocked ImageChecker
//		mockedImageChecker := &ImageCheckerMock{
//			CheckImageExistsFunc: func(ctx context.Context, imageURL string) (bool, error) {
//				panic("mock out the CheckImageExists method")
//			},
//		}
//
//		// use mockedImageChecker in code that requires ImageChecker
//		// and then make assertions.
//
//	}
type ImageCheckerMock struct {
	// CheckImageExistsFunc mocks the CheckImageExists method.
	CheckImageExistsFunc func(ctx context.Context, imageURL string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckImageExists holds details about calls to the CheckImageExists method.
		CheckImageExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ImageURL is the imageURL argument value.
			ImageURL string
		}
	}
	lockCheckImageExists sync.RWMutex
}

// CheckImageExists calls CheckImageExistsFunc.
func (mock *ImageCheckerMock) CheckImageExists(ctx context.Context, imageURL string) (bool, error) {
	if mock.CheckImageExistsFunc == nil {
		panic("ImageCheckerMock.CheckImageExistsFunc: method is nil but ImageChecker.CheckImageExists was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ImageURL string
	}{
		Ctx:      ctx,
		ImageURL: imageURL,
	}
	mock.lockCheckImageExists.Lock()
	mock.calls.CheckImageExists = append(mock.calls.CheckImageExists, callInfo)
	mock.lockCheckImageExists.Unlock()
	return mock.CheckImageExistsFunc(ctx, imageURL)
}

// CheckImageExistsCalls gets all the calls that were made to CheckImageExists.
// Check the length with:
//
//	len(mockedImageChecker.CheckImageExistsCalls())
func (mock *ImageCheckerMock) CheckImageExistsCalls() []struct {
	Ctx      context.Context
	ImageURL string
} {
	var calls []struct {
		Ctx      context.Context
		ImageURL string
	}
	mock.lockCheckImageExists.RLock()
	calls = mock.calls.CheckImageExists
	mock.lockCheckImageExists.RUnlock()
	return calls
}
