- name: kubernetes.virtualization.vm_annotation_monitoring
  rules:
    - alert: D8VirtualizationVMWithoutUniqueMacAddress
      expr: d8_virtualization_virtualmachine_annotation{annotation_key="virtualization.deckhouse.io/migration-to-mac-addresses", annotation_value="false"} == 1
      labels:
        severity_level: "6"
        tier: cluster
      for: 10m
      annotations:
        plk_protocol_version: "1"
        plk_markup_format: "markdown"
        plk_create_group_if_not_exists__d8_virtualization_vm_annotation_migration_to_mac_addresses_false: "D8VirtualizationVMAnnotationMigrationToMacAddressesFalse,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_virtualization_vm_annotation_migration_to_mac_addresses_false: "D8VirtualizationVMAnnotationMigrationToMacAddressesFalse,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: VirtualMachine resource with problematic annotation detected.
        description: |
          A VirtualMachine resource has been detected with the annotation "virtualization.deckhouse.io/migration-to-mac-addresses" set to "false".
          Recommended action:
          - Reset the network configuration on the VM.
          - Manually remove the annotation.
          - Restart the VM.
