{{- if (.Values.global.enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-cdi
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list $ (dict "prometheus" "main")) | nindent 2 }}
spec:
  endpoints:
  - bearerTokenSecret:
      key: token
      name: prometheus-token
    path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    metricRelabelings:
      # rename kubevirt_cdi_* -> d8_internal_virtualization_kubevirt_cdi_*
      - action: replace
        regex: kubevirt_cdi_(.*)
        replacement: d8_internal_virtualization_kubevirt_cdi_$1
        sourceLabels:
          - __name__
        targetLabel: __name__
  namespaceSelector:
    matchNames:
    - d8-{{ .Chart.Name }}
  selector:
    matchLabels:
      prometheus.cdi.internal.virtualization.deckhouse.io: "true"
{{- end }}
