// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package internal

import (
	"context"
	"github.com/deckhouse/virtualization/api/core/v1alpha2"
	virtv1 "kubevirt.io/api/core/v1"
	"sync"
)

// Ensure, that AttachmentServiceMock does implement AttachmentService.
// If this is not the case, regenerate this file with moq.
var _ AttachmentService = &AttachmentServiceMock{}

// AttachmentServiceMock is a mock implementation of AttachmentService.
//
//	func TestSomethingThatUsesAttachmentService(t *testing.T) {
//
//		// make and configure a mocked AttachmentService
//		mockedAttachmentService := &AttachmentServiceMock{
//			GetKVVMFunc: func(ctx context.Context, vm *v1alpha2.VirtualMachine) (*virtv1.VirtualMachine, error) {
//				panic("mock out the GetKVVM method")
//			},
//			GetKVVMIFunc: func(ctx context.Context, vm *v1alpha2.VirtualMachine) (*virtv1.VirtualMachineInstance, error) {
//				panic("mock out the GetKVVMI method")
//			},
//			GetVirtualMachineFunc: func(ctx context.Context, name string, namespace string) (*v1alpha2.VirtualMachine, error) {
//				panic("mock out the GetVirtualMachine method")
//			},
//		}
//
//		// use mockedAttachmentService in code that requires AttachmentService
//		// and then make assertions.
//
//	}
type AttachmentServiceMock struct {
	// GetKVVMFunc mocks the GetKVVM method.
	GetKVVMFunc func(ctx context.Context, vm *v1alpha2.VirtualMachine) (*virtv1.VirtualMachine, error)

	// GetKVVMIFunc mocks the GetKVVMI method.
	GetKVVMIFunc func(ctx context.Context, vm *v1alpha2.VirtualMachine) (*virtv1.VirtualMachineInstance, error)

	// GetVirtualMachineFunc mocks the GetVirtualMachine method.
	GetVirtualMachineFunc func(ctx context.Context, name string, namespace string) (*v1alpha2.VirtualMachine, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetKVVM holds details about calls to the GetKVVM method.
		GetKVVM []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VM is the vm argument value.
			VM *v1alpha2.VirtualMachine
		}
		// GetKVVMI holds details about calls to the GetKVVMI method.
		GetKVVMI []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VM is the vm argument value.
			VM *v1alpha2.VirtualMachine
		}
		// GetVirtualMachine holds details about calls to the GetVirtualMachine method.
		GetVirtualMachine []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Namespace is the namespace argument value.
			Namespace string
		}
	}
	lockGetKVVM           sync.RWMutex
	lockGetKVVMI          sync.RWMutex
	lockGetVirtualMachine sync.RWMutex
}

// GetKVVM calls GetKVVMFunc.
func (mock *AttachmentServiceMock) GetKVVM(ctx context.Context, vm *v1alpha2.VirtualMachine) (*virtv1.VirtualMachine, error) {
	if mock.GetKVVMFunc == nil {
		panic("AttachmentServiceMock.GetKVVMFunc: method is nil but AttachmentService.GetKVVM was just called")
	}
	callInfo := struct {
		Ctx context.Context
		VM  *v1alpha2.VirtualMachine
	}{
		Ctx: ctx,
		VM:  vm,
	}
	mock.lockGetKVVM.Lock()
	mock.calls.GetKVVM = append(mock.calls.GetKVVM, callInfo)
	mock.lockGetKVVM.Unlock()
	return mock.GetKVVMFunc(ctx, vm)
}

// GetKVVMCalls gets all the calls that were made to GetKVVM.
// Check the length with:
//
//	len(mockedAttachmentService.GetKVVMCalls())
func (mock *AttachmentServiceMock) GetKVVMCalls() []struct {
	Ctx context.Context
	VM  *v1alpha2.VirtualMachine
} {
	var calls []struct {
		Ctx context.Context
		VM  *v1alpha2.VirtualMachine
	}
	mock.lockGetKVVM.RLock()
	calls = mock.calls.GetKVVM
	mock.lockGetKVVM.RUnlock()
	return calls
}

// GetKVVMI calls GetKVVMIFunc.
func (mock *AttachmentServiceMock) GetKVVMI(ctx context.Context, vm *v1alpha2.VirtualMachine) (*virtv1.VirtualMachineInstance, error) {
	if mock.GetKVVMIFunc == nil {
		panic("AttachmentServiceMock.GetKVVMIFunc: method is nil but AttachmentService.GetKVVMI was just called")
	}
	callInfo := struct {
		Ctx context.Context
		VM  *v1alpha2.VirtualMachine
	}{
		Ctx: ctx,
		VM:  vm,
	}
	mock.lockGetKVVMI.Lock()
	mock.calls.GetKVVMI = append(mock.calls.GetKVVMI, callInfo)
	mock.lockGetKVVMI.Unlock()
	return mock.GetKVVMIFunc(ctx, vm)
}

// GetKVVMICalls gets all the calls that were made to GetKVVMI.
// Check the length with:
//
//	len(mockedAttachmentService.GetKVVMICalls())
func (mock *AttachmentServiceMock) GetKVVMICalls() []struct {
	Ctx context.Context
	VM  *v1alpha2.VirtualMachine
} {
	var calls []struct {
		Ctx context.Context
		VM  *v1alpha2.VirtualMachine
	}
	mock.lockGetKVVMI.RLock()
	calls = mock.calls.GetKVVMI
	mock.lockGetKVVMI.RUnlock()
	return calls
}

// GetVirtualMachine calls GetVirtualMachineFunc.
func (mock *AttachmentServiceMock) GetVirtualMachine(ctx context.Context, name string, namespace string) (*v1alpha2.VirtualMachine, error) {
	if mock.GetVirtualMachineFunc == nil {
		panic("AttachmentServiceMock.GetVirtualMachineFunc: method is nil but AttachmentService.GetVirtualMachine was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Name      string
		Namespace string
	}{
		Ctx:       ctx,
		Name:      name,
		Namespace: namespace,
	}
	mock.lockGetVirtualMachine.Lock()
	mock.calls.GetVirtualMachine = append(mock.calls.GetVirtualMachine, callInfo)
	mock.lockGetVirtualMachine.Unlock()
	return mock.GetVirtualMachineFunc(ctx, name, namespace)
}

// GetVirtualMachineCalls gets all the calls that were made to GetVirtualMachine.
// Check the length with:
//
//	len(mockedAttachmentService.GetVirtualMachineCalls())
func (mock *AttachmentServiceMock) GetVirtualMachineCalls() []struct {
	Ctx       context.Context
	Name      string
	Namespace string
} {
	var calls []struct {
		Ctx       context.Context
		Name      string
		Namespace string
	}
	mock.lockGetVirtualMachine.RLock()
	calls = mock.calls.GetVirtualMachine
	mock.lockGetVirtualMachine.RUnlock()
	return calls
}
