{
 "title": "VirtAudit",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Manage VM events count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (count_over_time({namespace=\"d8-virtualization\", pod=~\"virtualization-audit-.+\"} | json | type=\"Manage VM\" [$__auto]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Event level count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({namespace=\"d8-virtualization\", pod=~\"virtualization-audit-.+\"} | json [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Event type count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time({namespace=\"d8-virtualization\", pod=~\"virtualization-audit-.+\"} | json [$__auto]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "request_subject",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (request_subject) (count_over_time({namespace=\"d8-virtualization\", pod=~\"virtualization-audit-.+\"} | json [$__auto]))",
     "legendFormat": "{{request_subject}}"
    }
   ]
  },
  {
   "title": "Event actions with operation allow count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (action_type) (count_over_time({namespace=\"d8-virtualization\", pod=~\"virtualization-audit-.+\"} | json | operation_result=\"allow\" [$__auto]))",
     "legendFormat": "{{action_type}}"
    }
   ]
  },
  {
   "title": "Event actions with operation deny count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (action_type) (count_over_time({namespace=\"d8-virtualization\", pod=~\"virtualization-audit-.+\"} | json | operation_result=\"deny\" [$__auto]))",
     "legendFormat": "{{action_type}}"
    }
   ]
  },
  {
   "title": "Logs view",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{namespace=\"d8-virtualization\", pod=~\"virtualization-audit-.+\"} | json"
    }
   ]
  }
 ]
}