{{- if .Values.virtualization.usbipCIDR }}
apiVersion: usbgateway.virtualization.deckhouse.io/v1alpha1
kind: WireguardSystemNetwork
metadata:
  name: usbip
  namespace: d8-{{ .Chart.Name }}
spec:
  cidr: {{ .Values.virtualization.usbipCIDR }}
  listenPort: 51820 # TODO: hardcode
  interfaceName: usbip-wg0
{{- end }}
