/*
Copyright 2026 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package observer provides a generic, watch-based utility for monitoring the
// lifecycle of a single Kubernetes resource.
//
// The observer subscribes to events for a particular (name, namespace) pair
// and exposes three primitives:
//
//   - WaitFor blocks until the predicate is satisfied by an event observed
//     after the call, returns the predicate's diagnostic error, the timeout
//     elapses, or one of the registered Always/Never invariants fires.
//   - Never and Always register live predicates that are evaluated against
//     every event recorded after the call, directly inside the watch loop.
//     The very first violation is captured in Err and aborts every WaitFor
//     currently in flight.
//
// Predicates use the [Predicate] signature, returning a (bool, error) tuple:
//
//   - (true, nil)  - the predicate is satisfied by the current state.
//   - (false, nil) - the predicate is not satisfied yet. WaitFor keeps
//     waiting; an Always invariant treats this as a violation; a Never
//     invariant treats this as ok.
//   - (_, err)     - the predicate detected a definite, irrecoverable
//     inconsistency. The error is propagated to WaitFor or used as the
//     diagnostic for an Always/Never invariant violation.
package observer

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
)

// Watcher is the minimum interface required to start a watch on a Kubernetes
// resource. It matches typed clients generated by client-gen and the helpers
// already used by the e2e suite.
type Watcher interface {
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

// Object is the type constraint for resources that can be observed. The
// observed type must be a pointer that implements metav1.Object so that the
// observer can filter watch events by name and namespace.
type Object interface {
	metav1.Object
}

// Predicate evaluates an observed state of T. See the package documentation
// for the meaning of the (bool, error) return value.
type Predicate[T Object] func(T) (bool, error)

// Observer monitors a single Kubernetes resource through a watch and exposes
// invariant helpers over the sequence of states it observes.
//
// Implementations are safe for concurrent use.
type Observer[T Object] interface {
	// Never registers a forbidden predicate. While the observer is running,
	// every event is evaluated; the first time the predicate returns
	// (true, _) or (_, err) the observer captures the violation in Err and
	// aborts every WaitFor currently in flight. Never returns immediately and
	// does not consult past history: only events recorded after the call are
	// evaluated.
	Never(predicate Predicate[T])
	// Always registers an invariant predicate. While the observer is
	// running, every event is evaluated; the first time the predicate
	// returns (false, _) or (_, err) the observer captures the violation in
	// Err and aborts every WaitFor currently in flight. Always returns
	// immediately and does not consult past history: only events recorded
	// after the call are evaluated.
	Always(predicate Predicate[T])
	// WaitFor returns nil as soon as the predicate returns (true, nil) for
	// an event observed after the call. It returns an error if the predicate
	// returns a non-nil error, the timeout elapses, the observer is stopped,
	// or one of the registered invariants is violated. WaitFor does not
	// consult past history.
	WaitFor(predicate Predicate[T], timeout time.Duration) error
	// Err returns the first invariant violation captured by Never or Always,
	// or nil if no invariant has been violated. Once Err returns a non-nil
	// error, no further events are evaluated against any registered
	// invariant.
	Err() error
	// Stop terminates the underlying watch and unblocks every pending WaitFor
	// call. Stop is idempotent and safe to call concurrently from multiple
	// goroutines.
	Stop()
}

// New starts a watch via w and observes events for the resource identified by
// (name, namespace). The returned Observer is already running; the caller must
// invoke Stop to release the underlying watch.
//
// The watch is started before any caller-visible action takes place, which
// makes the function suitable for capturing the very first events emitted for
// a resource that the test is about to create.
func New[T Object](
	parentCtx context.Context,
	w Watcher,
	name, namespace string,
) (Observer[T], error) {
	if w == nil {
		return nil, errors.New("observer: watcher is nil")
	}

	ctx, cancel := context.WithCancel(parentCtx)
	wi, err := w.Watch(ctx, metav1.ListOptions{})
	if err != nil {
		cancel()
		return nil, fmt.Errorf("observer: start watch for %s/%s: %w", namespace, name, err)
	}

	o := &observer[T]{
		name:              name,
		namespace:         namespace,
		listeners:         make(map[chan T]struct{}),
		invariantViolated: make(chan struct{}),
		stop:              make(chan struct{}),
		done:              make(chan struct{}),
	}

	go o.run(wi, cancel)

	return o, nil
}

type observer[T Object] struct {
	name      string
	namespace string

	mu        sync.Mutex
	listeners map[chan T]struct{}

	invMu             sync.Mutex
	neverPredicates   []Predicate[T]
	alwaysPredicates  []Predicate[T]
	firstErr          error
	invariantViolated chan struct{}
	invariantOnce     sync.Once

	stop     chan struct{}
	stopOnce sync.Once
	done     chan struct{}
}

func (o *observer[T]) run(wi watch.Interface, cancel context.CancelFunc) {
	defer close(o.done)
	defer wi.Stop()
	defer cancel()

	for {
		select {
		case <-o.stop:
			return
		case event, ok := <-wi.ResultChan():
			if !ok {
				return
			}
			obj, ok := event.Object.(T)
			if !ok {
				continue
			}
			if obj.GetName() != o.name || obj.GetNamespace() != o.namespace {
				continue
			}
			o.broadcast(obj)
			o.checkInvariants(obj)
		}
	}
}

// broadcast forwards the event to every active WaitFor listener.
func (o *observer[T]) broadcast(obj T) {
	o.mu.Lock()
	defer o.mu.Unlock()

	for ch := range o.listeners {
		select {
		case ch <- obj:
		default:
			// Listener buffer is full; drop the event for this listener.
			// WaitFor predicates are typically simple and never block, so
			// this branch should not be reached in practice.
		}
	}
}

// checkInvariants evaluates every registered Never/Always predicate against
// the latest observation. The first violation latches firstErr and closes
// invariantViolated, which causes any WaitFor currently in flight to abort
// with the captured error.
//
// Predicates are evaluated sequentially inside the watch goroutine so that
// stateful closures see events in the order they were emitted by the API
// server. After the first violation no further predicates are evaluated for
// any subsequent event.
func (o *observer[T]) checkInvariants(obj T) {
	o.invMu.Lock()
	defer o.invMu.Unlock()

	if o.firstErr != nil {
		return
	}

	for _, p := range o.neverPredicates {
		ok, err := p(obj)
		if err != nil {
			o.firstErr = fmt.Errorf("observer: Never predicate: %w", err)
			o.signalViolationLocked()
			return
		}
		if ok {
			o.firstErr = errors.New("observer: Never predicate matched a live observation")
			o.signalViolationLocked()
			return
		}
	}
	for _, p := range o.alwaysPredicates {
		ok, err := p(obj)
		if err != nil {
			o.firstErr = fmt.Errorf("observer: Always predicate: %w", err)
			o.signalViolationLocked()
			return
		}
		if !ok {
			o.firstErr = errors.New("observer: Always predicate did not hold for a live observation")
			o.signalViolationLocked()
			return
		}
	}
}

// signalViolationLocked closes the invariantViolated channel exactly once.
// Must be called with invMu held.
func (o *observer[T]) signalViolationLocked() {
	o.invariantOnce.Do(func() {
		close(o.invariantViolated)
	})
}

func (o *observer[T]) Never(predicate Predicate[T]) {
	o.invMu.Lock()
	defer o.invMu.Unlock()
	o.neverPredicates = append(o.neverPredicates, predicate)
}

func (o *observer[T]) Always(predicate Predicate[T]) {
	o.invMu.Lock()
	defer o.invMu.Unlock()
	o.alwaysPredicates = append(o.alwaysPredicates, predicate)
}

func (o *observer[T]) Err() error {
	o.invMu.Lock()
	defer o.invMu.Unlock()
	return o.firstErr
}

func (o *observer[T]) WaitFor(predicate Predicate[T], timeout time.Duration) error {
	// If an invariant has already fired, abort immediately.
	if err := o.Err(); err != nil {
		return fmt.Errorf("observer: WaitFor aborted by invariant: %w", err)
	}

	// If the observer has already been stopped, no future events will arrive.
	select {
	case <-o.done:
		return errors.New("observer: WaitFor: observer is stopped")
	default:
	}

	o.mu.Lock()
	ch := make(chan T, 256)
	o.listeners[ch] = struct{}{}
	o.mu.Unlock()

	defer func() {
		o.mu.Lock()
		delete(o.listeners, ch)
		o.mu.Unlock()
	}()

	timer := time.NewTimer(timeout)
	defer timer.Stop()

	for {
		select {
		case obj := <-ch:
			ok, err := predicate(obj)
			if err != nil {
				return fmt.Errorf("observer: WaitFor predicate: %w", err)
			}
			if ok {
				return nil
			}
		case <-timer.C:
			return fmt.Errorf("observer: WaitFor timed out after %s", timeout)
		case <-o.done:
			return errors.New("observer: WaitFor: observer stopped before predicate became true")
		case <-o.invariantViolated:
			return fmt.Errorf("observer: WaitFor aborted by invariant: %w", o.Err())
		}
	}
}

func (o *observer[T]) Stop() {
	o.stopOnce.Do(func() {
		close(o.stop)
	})
	<-o.done
}
