#!/usr/bin/env bash

# Copyright 2026 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Script to generate NodeGroupConfiguration for dummy_hcd virtual USB devices
# Usage: ./generate_dummy_hcd_ngc.sh [count] [disk_size] [filesystem]
#   count       - number of virtual USB devices (default: 5)
#   disk_size   - size of each disk image (default: 64M, supports M or G suffix)
#   filesystem  - filesystem type: vfat, ext4 (default: vfat)

set -e

NUM_USB_DEVICES="${1:-5}"
DISK_SIZE="${2:-64M}"
FILESYSTEM="${3:-vfat}"

# Parse disk size to megabytes
parse_disk_size() {
  local size="$1"
  local num="${size%[MG]}"
  local unit="${size: -1}"
  case "$unit" in
    G) echo $((num * 1024)) ;;
    M) echo "$num" ;;
    *) echo "$num" ;;
  esac
}

DISK_COUNT=$(parse_disk_size "$DISK_SIZE")

# Validate filesystem
case "$FILESYSTEM" in
  vfat|ext4|ntfs) ;;
  *) echo "Error: filesystem must be vfat, ext4, or ntfs" >&2; exit 1 ;;
esac

cat <<EOF
apiVersion: deckhouse.io/v1alpha1
kind: NodeGroupConfiguration
metadata:
  name: virtualization-setup-dummy-hcd
  labels:
    heritage: deckhouse
    module: virtualization
    job: virtualization-setup-dummy-hcd
spec:
  bundles:
    - '*'
  nodeGroups:
    - '*'
  weight: 30
  content: |
    # Setup dummy_hcd kernel module for virtual USB devices (e2e tests)
    # Generated by test/e2e/scripts/generate_dummy_hcd_ngc.sh

    set -e

    KERNEL_VERSION="\$(uname -r)"
    NUM_USB_DEVICES=$NUM_USB_DEVICES
    DISK_SIZE="$DISK_SIZE"
    DISK_COUNT=$DISK_COUNT
    FILESYSTEM="$FILESYSTEM"
    WORK_DIR="/var/lib/dummy-hcd"
    USB_IMAGES_DIR="\$WORK_DIR/images"

    # Create work directory early to avoid issues
    mkdir -p "\$WORK_DIR"
    mkdir -p "\$USB_IMAGES_DIR"

    bb-log-info "Setting up dummy_hcd for \$NUM_USB_DEVICES virtual USB devices (filesystem: \$FILESYSTEM)"

    # Detect OS and install required packages
    bundle="\$(bb-is-bundle)"

    if [[ "\$bundle" == "altlinux" ]]; then
      # Alt Linux
      bb-log-info "Installing packages for Alt Linux"
      bb-pkg install kernel-modules-std-def build-essential git || true
      # Filesystem tools
      case "\$FILESYSTEM" in
        vfat) bb-pkg install dosfstools || true ;;
        ext4) bb-pkg install e2fsprogs || true ;;
        ntfs) bb-pkg install ntfs-3g || true ;;
      esac

    elif bb-is-distro-like? "debian"; then
      # Debian, Ubuntu, Astra (Debian-based)
      bb-log-info "Installing packages for Debian-based OS"
      bb-pkg install linux-headers-\$KERNEL_VERSION build-essential git libelf-dev || true
      case "\$FILESYSTEM" in
        vfat) bb-pkg install dosfstools || true ;;
        ext4) bb-pkg install e2fsprogs || true ;;
        ntfs) bb-pkg install ntfs-3g || true ;;
      esac

    elif bb-is-distro-like? "rhel" || bb-is-distro-like? "centos" || bb-is-distro-like? "fedora"; then
      # RHEL, CentOS, Fedora, ROSA, REDOS
      bb-log-info "Installing packages for RHEL-based OS"
      bb-pkg install kernel-devel-\$KERNEL_VERSION gcc make elfutils-libelf-devel git || true
      case "\$FILESYSTEM" in
        vfat) bb-pkg install dosfstools || true ;;
        ext4) bb-pkg install e2fsprogs || true ;;
        ntfs) bb-pkg install ntfs-3g || true ;;
      esac

    else
      bb-log-warn "Unsupported OS for dummy_hcd module build: bundle=\${bundle}"
      exit 1
    fi

    # Load required kernel modules
    bb-log-info "Loading kernel modules: libcomposite, udc_core"
    modprobe libcomposite || true
    modprobe udc_core || true

    # Check if dummy_hcd is already built and loaded
    if lsmod | grep -q "^dummy_hcd"; then
      bb-log-info "dummy_hcd module already loaded"
    else
      # Try to load pre-built module if exists
      if [ -f "/lib/modules/\$KERNEL_VERSION/extra/dummy_hcd.ko" ]; then
        bb-log-info "Loading pre-built dummy_hcd module"
        insmod /lib/modules/\$KERNEL_VERSION/extra/dummy_hcd.ko num=\$NUM_USB_DEVICES || true
      fi

      # If still not loaded, build from source
      if ! lsmod | grep -q "^dummy_hcd"; then
        bb-log-info "Building dummy_hcd module from source"

        # Clone and build raw-gadget
        if [ ! -d "\$WORK_DIR/raw-gadget" ]; then
          bb-log-info "Cloning raw-gadget repository"
          git clone https://github.com/xairy/raw-gadget "\$WORK_DIR/raw-gadget" || {
            bb-log-error "Failed to clone raw-gadget repository"
            exit 1
          }
        else
          bb-log-info "raw-gadget already cloned, skipping"
        fi

        cd "\$WORK_DIR/raw-gadget/dummy_hcd"

        # Update for current kernel version
        bb-log-info "Updating dummy_hcd for kernel \$KERNEL_VERSION"
        ./update.sh "\$(echo \$KERNEL_VERSION | cut -d. -f1,2)" || true

        # Build module
        bb-log-info "Building dummy_hcd.ko"
        make clean || true
        make -j\$(nproc) || {
          bb-log-error "Failed to build dummy_hcd module"
          exit 1
        }

        # Load module directly (no make modules_install in dummy_hcd)
        bb-log-info "Loading dummy_hcd module with num=\$NUM_USB_DEVICES"
        insmod ./dummy_hcd.ko num=\$NUM_USB_DEVICES || {
          bb-log-error "Failed to load dummy_hcd module"
          exit 1
        }
      fi
    fi

    # Verify module is loaded
    if ! lsmod | grep -q "^dummy_hcd"; then
      bb-log-error "dummy_hcd module is not loaded after setup"
      exit 1
    fi

    bb-log-info "dummy_hcd module loaded successfully"

    # Create USB images directory
    mkdir -p "\$USB_IMAGES_DIR"

    # Function to format disk image
    format_disk() {
      local img_file="\$1"
      local fs="\$2"

      case "\$fs" in
        vfat)
          bb-log-info "Formatting \$img_file as vfat"
          mkfs.vfat -F 32 "\$img_file" >/dev/null 2>&1 || {
            bb-log-warn "Failed to format as FAT32, trying FAT16"
            mkfs.vfat -F 16 "\$img_file" >/dev/null 2>&1 || true
          }
          ;;
        ext4)
          bb-log-info "Formatting \$img_file as ext4"
          mkfs.ext4 -F "\$img_file" >/dev/null 2>&1 || true
          ;;
        ntfs)
          bb-log-info "Formatting \$img_file as ntfs"
          mkfs.ntfs -f "\$img_file" >/dev/null 2>&1 || true
          ;;
      esac
    }

    # Create disk images if they don't exist
    bb-log-info "Creating \$NUM_USB_DEVICES disk images in \$USB_IMAGES_DIR (size: \$DISK_SIZE, fs: \$FILESYSTEM)"
    for i in \$(seq 1 \$NUM_USB_DEVICES); do
      IMG_FILE="\$USB_IMAGES_DIR/disk\${i}.img"
      if [ ! -f "\$IMG_FILE" ]; then
        bb-log-info "Creating disk\${i}.img (\${DISK_SIZE})"
        dd if=/dev/zero of="\$IMG_FILE" bs=1M count=\$DISK_COUNT status=none
        # Format with selected filesystem
        format_disk "\$IMG_FILE" "\$FILESYSTEM"
      else
        bb-log-info "disk\${i}.img already exists, skipping"
      fi
    done

    # Setup USB gadgets using configfs
    bb-log-info "Setting up USB gadgets via configfs"

    # Ensure configfs is mounted (check if already mounted first)
    if mount | grep -q "configfs"; then
      bb-log-info "configfs already mounted"
    elif mountpoint -q /sys/kernel/config; then
      bb-log-info "configfs already mounted at /sys/kernel/config"
    else
      mount -t configfs none /sys/kernel/config || {
        bb-log-warn "Failed to mount configfs, it may be mounted elsewhere"
      }
    fi

    GADGET_PATH="/sys/kernel/config/usb_gadget"

    # Function to create a virtual USB device
    make_flash() {
      local n="\$1"
      local img_file="\$2"

      local gadget_name="g\${n}"
      local gadget_dir="\$GADGET_PATH/\$gadget_name"
      local udc_name="dummy_udc.\$((n-1))"

      # Check if gadget already exists
      if [ -d "\$gadget_dir" ]; then
        bb-log-info "Gadget \$gadget_name already exists, skipping"
        return 0
      fi

      bb-log-info "Creating USB gadget \$gadget_name"

      mkdir -p "\$gadget_dir"

      # Set VID/PID (test values)
      echo 0x1d6b > "\$gadget_dir/idVendor"
      echo 0x0104 > "\$gadget_dir/idProduct"

      # Set strings
      mkdir -p "\$gadget_dir/strings/0x409"
      echo "FLASH\$n" > "\$gadget_dir/strings/0x409/serialnumber"
      echo "dummy" > "\$gadget_dir/strings/0x409/manufacturer"
      echo "Flash \$n" > "\$gadget_dir/strings/0x409/product"

      # Create configuration
      mkdir -p "\$gadget_dir/configs/c.1/strings/0x409"
      echo "cfg" > "\$gadget_dir/configs/c.1/strings/0x409/configuration"

      # Create mass storage function
      mkdir -p "\$gadget_dir/functions/mass_storage.usb0"
      echo 1 > "\$gadget_dir/functions/mass_storage.usb0/stall"
      echo 1 > "\$gadget_dir/functions/mass_storage.usb0/lun.0/removable"
      echo 0 > "\$gadget_dir/functions/mass_storage.usb0/lun.0/ro"
      echo "\$img_file" > "\$gadget_dir/functions/mass_storage.usb0/lun.0/file"

      # Link function to configuration
      ln -s "\$gadget_dir/functions/mass_storage.usb0" "\$gadget_dir/configs/c.1/"

      # Bind to UDC
      echo "\$udc_name" > "\$gadget_dir/UDC"

      bb-log-info "USB gadget \$gadget_name created and bound to \$udc_name"
    }

    # Create USB gadgets for each device
    for i in \$(seq 1 \$NUM_USB_DEVICES); do
      make_flash "\$i" "\$USB_IMAGES_DIR/disk\${i}.img"
    done

    bb-log-info "dummy_hcd setup completed successfully"
EOF
