{
 "title": "Namespace / Virtual Machine",
 "tags": [ "main" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_status_phase,namespace)"
    }
   },
   {
    "name": "name",
    "label": "Machine name",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_status_phase{namespace=\"$namespace\"},name)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_network_receive_bytes_total{namespace=\"$namespace\", name=\"$name\"},network)"
    }
   },
   {
    "name": "mount_point",
    "label": "Mountpoint",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_filesystem_capacity_bytes{namespace=\"$namespace\", name=\"$name\", mount_point!~\".*(/var/lib/containerd/io.containerd.snapshotter.v1.erofs|/var/lib/kubelet/pods).*\"},mount_point)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Shows the current status of the virtual machine including Running, Stopped, Migrating, and other operational states.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (\n  max by (name,pod) (\n    (d8_virtualization_virtualmachine_status_phase{namespace=\"$namespace\", name=\"$name\"} == 1) * on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Degraded\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Migrating\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Pause\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(6), \"phase\", \"Starting\", \"\", \"\") or\n        label_replace(vector(7), \"phase\", \"Stopped\", \"\", \"\") or\n        label_replace(vector(8), \"phase\", \"Stopping\", \"\", \"\") or\n        label_replace(vector(9), \"phase\", \"Terminating\", \"\", \"\")\n      ))\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Node name",
   "type": "stat",
   "description": "The node on which the VM is currently running",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "d8_virtualization_virtualmachine_info{namespace=\"$namespace\", name=\"$name\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMClass",
   "type": "stat",
   "description": "The VMClass that is actually applied to the running VM. May differ from spec.virtualMachineClassName if VM was not restarted after spec change.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "d8_virtualization_virtualmachine_info{namespace=\"$namespace\", name=\"$name\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU core usage",
   "type": "gauge",
   "description": "Shows the current CPU core usage percentage of the virtual machine, including OS usage, hypervisor overhead, and CPU reservation levels.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace,name) (rate(d8_virtualization_virtualmachine_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) \n/\n(\n    sum by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}) / 100\n)",
     "legendFormat": "OS Usage"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "description": "Displays the current memory usage percentage of the virtual machine based on configured memory allocation.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_os_memory_total_bytes - d8_virtualization_virtualmachine_os_memory_potentially_free_bytes{namespace=\"$namespace\", name=\"$name\"}) / (avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"}) / 100)",
     "legendFormat": "OS Usage"
    }
   ]
  },
  {
   "title": "Storage allocated",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  avg by (name, namespace)(\n    d8_virtualization_virtualdisk_capacity_bytes{namespace=~\"$namespace\"} \n    * on (name,namespace,pod) d8_virtualization_virtualdisk_status_in_use{virtualmachine=~\"$name\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (name,namespace) (\n  sum by (name, namespace,pod) (\n    d8_virtualization_virtualmachine_filesystem_capacity_bytes{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\",mount_point!~\".*(io.containerd.snapshotter.v1.erofs|/var/lib/kubelet/pods).*\"}\n  )\n)\n",
     "legendFormat": "Capacity"
    },
    {
     "expr": "avg by (name,namespace) (\n  sum by (name, namespace) (\n    d8_virtualization_virtualmachine_filesystem_used_bytes{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\",mount_point!~\".*(io.containerd.snapshotter.v1.erofs|/var/lib/kubelet/pods).*\"}\n  )\n)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Total filesystem usage",
   "type": "gauge",
   "description": "This graph displays the total disk usage across all disks in the system as a percentage. It aggregates data from every filesystem, summing up used space and total capacity to provide an overall view of disk utilization. The calculation excludes temporary or cloud-init files to ensure accuracy.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (name,namespace) (\n  sum by (name, namespace,pod) (\n    d8_virtualization_virtualmachine_filesystem_used_bytes{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\",mount_point!~\".*(io.containerd.snapshotter.v1.erofs|/var/lib/kubelet/pods).*\"})\n  / \n  sum by (name, namespace,pod) (d8_virtualization_virtualmachine_filesystem_capacity_bytes / 100)\n)\n",
     "legendFormat": "{{mount_point}}"
    }
   ]
  },
  {
   "title": "Agent",
   "type": "stat",
   "description": "Shows the agent readiness status for the virtual machine, indicating whether the VM agent is ready to receive commands.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (\n    count by (name,pod) (\n        d8_virtualization_virtualmachine_agent_ready{namespace=\"$namespace\", name=\"$name\"}\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Instance CPU core count",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks attached",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (namespace, name) (\n    count by (namespace, name,pod) (\n        label_replace(\n            d8_virtualization_virtualdisk_status_in_use{namespace=~\"$namespace\"}, \n            \"name\", \n            \"$1\", \n            \"virtualmachine\", \n            \"(.+)\"\n        )\n    ) * on(namespace, name,pod) group_left() (\n        d8_virtualization_virtualmachine_status_phase{namespace=~\"$namespace\",name=\"$name\"} == 1\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config",
   "type": "stat",
   "description": "Whether the desired configuration is currently applied to a running VM",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (\n    count by (name,pod) (\n        d8_virtualization_virtualmachine_configuration_applied{namespace=\"$namespace\", name=\"$name\"}\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Instance memory",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (namespace) (\n    count by (namespace,pod) (\n        d8_virtualization_virtualmachinesnapshot_info{namespace=~\"$namespace\", virtualmachine=\"$name\"}==1\n    )\n) or absent(d8_virtualization_virtualmachinesnapshot_info{namespace=~\"$namespace\", virtualmachine=\"$name\"}==1) * vector(0)",
     "legendFormat": "VM snapshots"
    }
   ]
  },
  {
   "title": "CPU Core usage in %",
   "type": "timeseries",
   "description": "Shows detailed CPU core usage metrics including OS usage, hypervisor overhead, and CPU reservation levels over time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (namespace,name) (\n    rate(\n        d8_virtualization_virtualmachine_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]\n    )\n) \n/\n(\n    avg by (namespace,name) (\n        sum by (namespace,name,pod) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}) / 100\n    )\n)",
     "legendFormat": "OS Usage"
    },
    {
     "expr": "(\n    sum by (namespace,name) (\n        rate(\n            d8_virtualization_virtualmachine_hypervisor_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]\n        )\n    )\n    - \n    sum by (namespace,name) (\n        rate(\n            d8_virtualization_virtualmachine_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]\n        )\n    )\n)\n/\n(\n    avg by (namespace,name) (\n        sum by (namespace,name,pod) (\n            d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}\n        ) / 100\n    )\n)",
     "legendFormat": "Hypervisor overhead"
    },
    {
     "expr": "avg by (namespace,name) (\n    (\n        sum by (namespace,name,pod) (\n            (\n                d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"} \n                * \n                d8_virtualization_virtualmachine_cpu_core_fraction\n            ) / 100\n        )\n    )\n    /\n    (\n        sum by (namespace,name,pod) (\n            d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}\n        ) / 100\n    )\n)\n\n",
     "legendFormat": "Reservation"
    }
   ]
  },
  {
   "title": "Memory usage in %",
   "type": "timeseries",
   "description": "Displays memory usage percentage over time, showing how much of the allocated memory is being used by the virtual machine.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_os_memory_total_bytes - d8_virtualization_virtualmachine_os_memory_potentially_free_bytes{namespace=\"$namespace\", name=\"$name\"}) / (avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"}) / 100)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Network bandwidth usage",
   "type": "timeseries",
   "description": "Shows network bandwidth utilization displaying transmit and receive data rates for all network interfaces in the virtual machine.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(d8_virtualization_virtualmachine_network_receive_bytes_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])*8)",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(d8_virtualization_virtualmachine_network_transmit_bytes_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])*8)",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk read IOPS",
   "type": "timeseries",
   "description": "Disk read I/O operations",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(d8_virtualization_virtualmachine_block_device_iops_read_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(d8_virtualization_virtualmachine_block_device_iops_write_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "VM status details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM status timeline",
     "type": "state-timeline",
     "description": "Timeline with information on VM statuses",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "max by (name) (\n  sum by (name,pod) (\n    (d8_virtualization_virtualmachine_status_phase{namespace=\"$namespace\", name=\"$name\"} == 1) * on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Degraded\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Migrating\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Pause\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(6), \"phase\", \"Starting\", \"\", \"\") or\n        label_replace(vector(7), \"phase\", \"Stopped\", \"\", \"\") or\n        label_replace(vector(8), \"phase\", \"Stopping\", \"\", \"\") or\n        label_replace(vector(9), \"phase\", \"Terminating\", \"\", \"\")\n      ))\n)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Configuration",
     "type": "state-timeline",
     "description": "Whether the desired configuration is currently applied to a running VM",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "max by (name) (\n    count by (name,pod) (\n        d8_virtualization_virtualmachine_configuration_applied{namespace=\"$namespace\", name=\"$name\"}\n    )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VM pods",
     "type": "table",
     "description": "Pods associated with this Virtual Machine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (max_over_time(kube_pod_labels{namespace=\"$namespace\", label_vm_kubevirt_internal_virtualization_deckhouse_io_name=\"$name\"}[$__range]))\nor\nmax by (pod) (\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Pod\"}\n  * on (owner_name) group_left()\n  label_replace(\n    max by (pod) (max_over_time(kube_pod_labels{namespace=\"$namespace\", label_vm_kubevirt_internal_virtualization_deckhouse_io_name=\"$name\"}[$__range])),\n    \"owner_name\",\n    \"$1\",\n    \"pod\",\n    \"(.*)\"\n  )\n)",
       "legendFormat": "Pod Name"
      },
      {
       "expr": "(\n  max by (pod) (max_over_time(kube_pod_labels{namespace=\"$namespace\", label_vm_kubevirt_internal_virtualization_deckhouse_io_name=\"$name\"}[$__range]))\n  or\n  max by (pod) (\n    kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Pod\"}\n    * on (owner_name) group_left()\n    label_replace(\n      max by (pod) (max_over_time(kube_pod_labels{namespace=\"$namespace\", label_vm_kubevirt_internal_virtualization_deckhouse_io_name=\"$name\"}[$__range])),\n      \"owner_name\",\n      \"$1\",\n      \"pod\",\n      \"(.*)\"\n    )\n  )\n)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod) (last_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[5m])) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (\n        (last_over_time(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"}[5m]) == 1) * 0 + 1\n        or\n        (last_over_time(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Pending\"}[5m]) == 1) * 0 + 2\n        or\n        (last_over_time(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Unknown\"}[5m]) == 1) * 0 + 3\n        or\n        (last_over_time(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Failed\"}[5m]) == 1) * 0 + 4\n        or\n        (last_over_time(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Succeeded\"}[5m]) == 1) * 0 + 5\n      )\n    )\n  )",
       "legendFormat": "Phase"
      },
      {
       "expr": "(max by (pod) (max_over_time(kube_pod_labels{namespace=\"$namespace\", label_vm_kubevirt_internal_virtualization_deckhouse_io_name=\"$name\"}[$__range]))\nor\nmax by (pod) (\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Pod\"}\n  * on (owner_name) group_left()\n  label_replace(\n    max by (pod) (max_over_time(kube_pod_labels{namespace=\"$namespace\", label_vm_kubevirt_internal_virtualization_deckhouse_io_name=\"$name\"}[$__range])),\n    \"owner_name\",\n    \"$1\",\n    \"pod\",\n    \"(.*)\"\n  )\n))\n  * on (pod) group_left()\n  (time() - kube_pod_created{namespace=\"$namespace\"})",
       "legendFormat": "Created"
      }
     ]
    },
    {
     "title": "VM operations",
     "type": "table",
     "description": "VM operations",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "last_over_time(d8_virtualization_virtualmachineoperation_created_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) * 1000 and on(uid) ((last_over_time(d8_virtualization_virtualmachineoperation_created_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_created_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000) or (last_over_time(d8_virtualization_virtualmachineoperation_started_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_started_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000) or (last_over_time(d8_virtualization_virtualmachineoperation_finished_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_finished_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000))",
       "legendFormat": "__auto"
      },
      {
       "expr": "last_over_time(d8_virtualization_virtualmachineoperation_started_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) * 1000 and on(uid) ((last_over_time(d8_virtualization_virtualmachineoperation_created_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_created_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000) or (last_over_time(d8_virtualization_virtualmachineoperation_started_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_started_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000) or (last_over_time(d8_virtualization_virtualmachineoperation_finished_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_finished_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000))",
       "legendFormat": "__auto"
      },
      {
       "expr": "last_over_time(d8_virtualization_virtualmachineoperation_finished_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) * 1000 and on(uid) ((last_over_time(d8_virtualization_virtualmachineoperation_created_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_created_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000) or (last_over_time(d8_virtualization_virtualmachineoperation_started_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_started_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000) or (last_over_time(d8_virtualization_virtualmachineoperation_finished_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_finished_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000))",
       "legendFormat": "__auto"
      },
      {
       "expr": "last_over_time(d8_virtualization_virtualmachineoperation_status_phase{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) == 1 and on(uid) ((last_over_time(d8_virtualization_virtualmachineoperation_created_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_created_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000) or (last_over_time(d8_virtualization_virtualmachineoperation_started_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_started_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000) or (last_over_time(d8_virtualization_virtualmachineoperation_finished_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) >= $__from/1000 and last_over_time(d8_virtualization_virtualmachineoperation_finished_timestamp_seconds{namespace=\"$namespace\", virtualmachine=\"$name\"}[$__range]) <= $__to/1000))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Live migration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live migration memory metrics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum(rate(d8_virtualization_virtualmachine_migration_data_processed_bytes{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) without (instance,job,node) * 8",
       "legendFormat": "Processed memory rate"
      },
      {
       "expr": "sum(rate(d8_virtualization_virtualmachine_migration_data_remaining_bytes{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) without (instance,job,node) * 8",
       "legendFormat": "Remaining memory rate"
      },
      {
       "expr": "sum(d8_virtualization_virtualmachine_migration_dirty_memory_rate_bytes{namespace=\"$namespace\", name=\"$name\"}) without (instance,job,node) * 8",
       "legendFormat": "Dirty memory rate"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Core usage",
     "type": "timeseries",
     "description": "`Current cores` - The amount of computing resources allocated to the virtual machine.\n\n`Guaranteed cores` - The minimum amount of resources (in fractions of CPUs) guaranteed to be available to the VM. Calculated as `Current cores` × `Reservation`\n\n`Hypervisor overhead` - The value of the fraction of CPU used by the hypervisor.\n\n`OS Usage` - The level of utilization of allocated compute resources of the guest OS. If `Reservation < 100%`, it is allowed to exceed `OS Usage` up to the value of `Current cores`.\n\n`Steal cores` - The value of CPU share that the virtual machine was waiting to access physical resources due to competition with other VMs (“noisy neighbors”).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace,name) (rate(d8_virtualization_virtualmachine_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "OS Usage"
      },
      {
       "expr": "rate(d8_virtualization_virtualmachine_hypervisor_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])\n- on(namespace, name) group_left()\nsum by(namespace, name) (rate(d8_virtualization_virtualmachine_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))\n\n",
       "legendFormat": "Hypervisor overhead"
      },
      {
       "expr": "avg by (namespace,name) (\n    sum by (namespace,name,pod) (\n        (\n            d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"} \n            * \n            d8_virtualization_virtualmachine_cpu_core_fraction\n        ) / 100\n    )\n)\n\n",
       "legendFormat": "Guaranteed cores"
      },
      {
       "expr": "avg by (namespace,name) (\n    sum by (namespace,name,pod) (\n        d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}\n    )\n)",
       "legendFormat": "Current cores"
      },
      {
       "expr": "sum by (namespace,name) (rate(d8_virtualization_virtualmachine_cpu_steal_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) ",
       "legendFormat": "Steal cores"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "timeseries",
     "description": "`Current cores` - The amount of computing resources allocated to a virtual machine.\n\n`Current cores guaranteed` - The minimum amount of resources (in fractions of CPUs) guaranteed to be available to the VM. Calculated as `Current cores` × `Reservation`.\n\n`Configured cores` - The amount of computing resources configured in the virtual machine which will be aplied after VM restart.\n\n`Configured cores guaranteed` - The minimum amount of resources (in CPU fractions) guaranteed to be available to the VM that will be available after the configuration is applied.\n\n`Demand cores` - The number of CPU shares by which it is recommended to increase `Current cores` based on the current load\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (namespace,name) (\n    sum by (namespace,name,pod) (\n        (\n            d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"} \n            * \n            d8_virtualization_virtualmachine_cpu_core_fraction\n        ) / 100\n    )\n)",
       "legendFormat": "Current cores guaranteed "
      },
      {
       "expr": "avg by (namespace,name) (\n    sum by (namespace,name,pod) (\n        (\n            d8_virtualization_virtualmachine_configuration_cpu_cores{namespace=\"$namespace\", name=\"$name\"} \n            * \n            d8_virtualization_virtualmachine_configuration_cpu_core_fraction\n        ) / 100\n    )\n)",
       "legendFormat": "Configured cores guaranteed "
      },
      {
       "expr": "avg by (namespace,name) (\n    sum by (namespace,name,pod) (\n        d8_virtualization_virtualmachine_configuration_cpu_cores{namespace=\"$namespace\", name=\"$name\"}\n    )\n)",
       "legendFormat": "Configured cores"
      },
      {
       "expr": "avg by (namespace,name) (\n    sum by (namespace,name,pod) (\n        d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}\n    )\n)",
       "legendFormat": "Current cores"
      },
      {
       "expr": "sum by (label_vm_kubevirt_internal_virtualization_deckhouse_io_name) (\n  sum by (namespace, pod) (\n    max by (namespace, pod) (\n      kube_controller_pod{}\n    ) \n    * \n    on (pod,namespace) sum by (namespace, pod) (\n      (\n        sum by (namespace, pod, container) (\n          rate(container_cpu_usage_seconds_total{}[$__rate_interval])\n        )\n        -\n        sum by (namespace, pod, container) (\n          avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",container!=\"POD\"}[$__rate_interval])\n        )\n      )\n    )\n  ) * on (namespace, pod) group_left(label_vm_kubevirt_internal_virtualization_deckhouse_io_name) (kube_pod_labels{namespace=\"$namespace\",label_vm_kubevirt_internal_virtualization_deckhouse_io_name=\"$name\"}) > 0\n)",
       "legendFormat": "Demand cores "
      }
     ]
    },
    {
     "title": "CPU usage per core",
     "type": "timeseries",
     "description": "`Current cores` - The amount of computing resources allocated to the virtual machine.\n\n`Guaranteed cores` - The minimum amount of resources (in fractions of CPUs) guaranteed to be available to the VM. Calculated as `Current cores` × `Reservation`\n\n`Hypervisor overhead` - The value of the fraction of CPU used by the hypervisor.\n\n`OS Usage` - The level of utilization of allocated compute resources of the guest OS. If `Reservation < 100%`, it is allowed to exceed `OS Usage` up to the value of `Current cores`.\n\n`Steal cores` - The value of CPU share that the virtual machine was waiting to access physical resources due to competition with other VMs (“noisy neighbors”).",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace,name,core) (rate(d8_virtualization_virtualmachine_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "OS Usage core {{ core }}"
      },
      {
       "expr": "rate(d8_virtualization_virtualmachine_hypervisor_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])\n- on(namespace, name) group_left()\nsum by(namespace, name) (rate(d8_virtualization_virtualmachine_cpu_usage_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))\n",
       "legendFormat": "Hypervisor overhead"
      },
      {
       "expr": "avg by (namespace,name) (\nsum by (namespace,name,pod) ((d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"} * d8_virtualization_virtualmachine_cpu_core_fraction) / 100)\n)",
       "legendFormat": "Guaranteed cores"
      },
      {
       "expr": "avg by (namespace,name) (\nsum by (namespace,name,pod) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"})\n)",
       "legendFormat": "Current cores"
      },
      {
       "expr": "sum by (namespace,name,core) (rate(d8_virtualization_virtualmachine_cpu_steal_seconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "Steal core {{ core }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "timeseries",
     "description": "Timeline visualization displaying the virtual machine status changes over time, including running, stopped, migrating, and other states.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "Configured memory"
      },
      {
       "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_os_memory_total_bytes - d8_virtualization_virtualmachine_os_memory_potentially_free_bytes{namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "OS used"
      }
     ]
    },
    {
     "title": "Memory ",
     "type": "timeseries",
     "description": "The current and configured amount of the memory to be applied after restart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "Memory current"
      },
      {
       "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_configuration_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "Memory configured"
      }
     ]
    },
    {
     "title": "Page faults",
     "type": "timeseries",
     "description": "Memory page faults for the VM instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "avg(rate(d8_virtualization_virtualmachine_os_memory_pgminfault_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "Minor"
      },
      {
       "expr": "avg(rate(d8_virtualization_virtualmachine_os_memory_pgmajfault_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "Major"
      }
     ]
    },
    {
     "title": "Swap traffic",
     "type": "timeseries",
     "description": "Amount of data swapped in/out by the VM instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg(rate(d8_virtualization_virtualmachine_os_memory_swap_in_traffic_bytes{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "IN"
      },
      {
       "expr": "avg(rate(d8_virtualization_virtualmachine_os_memory_swap_out_traffic_bytes{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "OUT"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage capacity details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual disks",
     "type": "table",
     "description": "Detailed table of all virtual disk with status information\n\n- `Pending` - waiting for all dependent resources required for disk creation to be ready.\n- `Provisioning` - disk creation process is in progress.\n- `Resizing` - the process of resizing the disk is in progress.\n- `WaitForFirstConsumer` - the disk is waiting for the virtual machine that will use it to be created.\n- `WaitForUserUpload` - the disk is waiting for the user to upload an image (type: Upload).\n- `Ready` - the disk has been created and is ready for use.\n- `Failed` - an error occurred during the creation process.\n- `PVCLost` - system error, PVC with data has been lost.\n- `Terminating` - the disk is being deleted. The disk may \"hang\" in this state if it is still connected to the virtual machine.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (namespace, name, phase) (d8_virtualization_virtualdisk_status_phase{namespace=\"$namespace\"})==1 and on(namespace, name) max by (namespace, name) (d8_virtualization_virtualdisk_status_in_use{namespace=\"$namespace\", virtualmachine=\"$name\"})",
       "legendFormat": "Virtual Machine"
      },
      {
       "expr": "max by (namespace, name) (d8_virtualization_virtualdisk_capacity_bytes{namespace=\"$namespace\"}) and on(namespace, name) max by (namespace, name) (d8_virtualization_virtualdisk_status_in_use{namespace=\"$namespace\", virtualmachine=\"$name\"})",
       "legendFormat": "Virtual Machine"
      },
      {
       "expr": "count by (namespace, name) (\n    label_replace(\n        d8_virtualization_virtualdisksnapshot_info{namespace=\"$namespace\"}, \n        \"name\", \n        \"$1\", \n        \"virtualdisk\", \n        \"(.+)\"\n    )\n) * on(namespace, name) group_left() (\n    d8_virtualization_virtualdisk_status_phase{namespace=\"$namespace\"} == 1\n) and on(namespace, name) max by (namespace, name) (d8_virtualization_virtualdisk_status_in_use{namespace=\"$namespace\", virtualmachine=\"$name\"})",
       "legendFormat": "Virtual Machine"
      },
      {
       "expr": "max by (namespace, name, storageclass) (d8_virtualization_virtualdisk_info{namespace=\"$namespace\"}) and on(namespace, name) max by (namespace, name) (d8_virtualization_virtualdisk_status_in_use{namespace=\"$namespace\", virtualmachine=\"$name\"})",
       "legendFormat": "Virtual Machine"
      }
     ]
    },
    {
     "title": "Storage usage ",
     "type": "timeseries",
     "description": "Chart showing changes in total storage usage by virtual machine. ",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (namespace,name) (\nd8_virtualization_virtualdisk_capacity_bytes{namespace=~\"$namespace\"} * on (name,pod,namespace) d8_virtualization_virtualdisk_status_in_use{virtualmachine=~\"$name\"}\n)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Mount point \"$mount_point\"",
     "type": "timeseries",
     "description": "Mount point usage and capacity",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
     "repeat": "mount_point",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(mount_point) (d8_virtualization_virtualmachine_filesystem_capacity_bytes{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\", mount_point=~\"$mount_point\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum by (mount_point) (d8_virtualization_virtualmachine_filesystem_used_bytes{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\", mount_point=~\"$mount_point\"})",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage I/O details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read IOPS",
     "type": "timeseries",
     "description": "Disk read I/O operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (rate(d8_virtualization_virtualmachine_block_device_iops_read_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk write IOPS",
     "type": "timeseries",
     "description": "Disk write I/O operations",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (rate(d8_virtualization_virtualmachine_block_device_iops_write_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk read latency",
     "type": "timeseries",
     "description": "Disk read operations latency",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (\n    rate(d8_virtualization_virtualmachine_block_device_read_times_seconds_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval])\n    /\n    rate(d8_virtualization_virtualmachine_block_device_iops_read_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval])\n)\n",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk write throughput",
     "type": "timeseries",
     "description": "Disk write traffic in bytes per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (rate(d8_virtualization_virtualmachine_block_device_write_traffic_bytes_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk read throughput",
     "type": "timeseries",
     "description": "Disk read traffic in bytes per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (rate(d8_virtualization_virtualmachine_block_device_read_traffic_bytes_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk write latency",
     "type": "timeseries",
     "description": "Disk write operations latency",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (\n    rate(d8_virtualization_virtualmachine_block_device_write_times_seconds_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval])\n    /\n    rate(d8_virtualization_virtualmachine_block_device_iops_write_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval])\n    )",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network \"$network\" details ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "network",
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth - $network",
     "type": "timeseries",
     "description": "Interface bandwidth",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_receive_bytes_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX bps"
      },
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_transmit_bytes_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX bps"
      }
     ]
    },
    {
     "title": "Packet rate - $network",
     "type": "timeseries",
     "description": "Packet rate on the interface",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_receive_packets_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX pps"
      },
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_transmit_packets_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX pps"
      }
     ]
    },
    {
     "title": "Packet drops - $network",
     "type": "timeseries",
     "description": "Packets dropped by the interface",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_receive_packets_dropped_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX drops"
      },
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_transmit_packets_dropped_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX drops"
      }
     ]
    },
    {
     "title": "Interface errors - $network",
     "type": "timeseries",
     "description": "Interface transmit and receive errors",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_receive_errors_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX errors"
      },
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_transmit_errors_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX errors"
      }
     ]
    }
   ]
  }
 ]
}