//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha3

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPU) DeepCopyInto(out *CPU) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Discovery.DeepCopyInto(&out.Discovery)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPU.
func (in *CPU) DeepCopy() *CPU {
	if in == nil {
		return nil
	}
	out := new(CPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CpuDiscovery) DeepCopyInto(out *CpuDiscovery) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CpuDiscovery.
func (in *CpuDiscovery) DeepCopy() *CpuDiscovery {
	if in == nil {
		return nil
	}
	out := new(CpuDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CpuFeatures) DeepCopyInto(out *CpuFeatures) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotEnabledCommon != nil {
		in, out := &in.NotEnabledCommon, &out.NotEnabledCommon
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CpuFeatures.
func (in *CpuFeatures) DeepCopy() *CpuFeatures {
	if in == nil {
		return nil
	}
	out := new(CpuFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryMinMax) DeepCopyInto(out *MemoryMinMax) {
	*out = *in
	out.Min = in.Min.DeepCopy()
	out.Max = in.Max.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryMinMax.
func (in *MemoryMinMax) DeepCopy() *MemoryMinMax {
	if in == nil {
		return nil
	}
	out := new(MemoryMinMax)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelector) DeepCopyInto(out *NodeSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]v1.NodeSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelector.
func (in *NodeSelector) DeepCopy() *NodeSelector {
	if in == nil {
		return nil
	}
	out := new(NodeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizingPolicy) DeepCopyInto(out *SizingPolicy) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(SizingPolicyMemory)
		(*in).DeepCopyInto(*out)
	}
	if in.CoreFractions != nil {
		in, out := &in.CoreFractions, &out.CoreFractions
		*out = make([]CoreFractionValue, len(*in))
		copy(*out, *in)
	}
	if in.DedicatedCores != nil {
		in, out := &in.DedicatedCores, &out.DedicatedCores
		*out = make([]bool, len(*in))
		copy(*out, *in)
	}
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = new(SizingPolicyCores)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizingPolicy.
func (in *SizingPolicy) DeepCopy() *SizingPolicy {
	if in == nil {
		return nil
	}
	out := new(SizingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizingPolicyCores) DeepCopyInto(out *SizingPolicyCores) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizingPolicyCores.
func (in *SizingPolicyCores) DeepCopy() *SizingPolicyCores {
	if in == nil {
		return nil
	}
	out := new(SizingPolicyCores)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizingPolicyMemory) DeepCopyInto(out *SizingPolicyMemory) {
	*out = *in
	in.MemoryMinMax.DeepCopyInto(&out.MemoryMinMax)
	out.Step = in.Step.DeepCopy()
	in.PerCore.DeepCopyInto(&out.PerCore)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizingPolicyMemory.
func (in *SizingPolicyMemory) DeepCopy() *SizingPolicyMemory {
	if in == nil {
		return nil
	}
	out := new(SizingPolicyMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizingPolicyMemoryPerCore) DeepCopyInto(out *SizingPolicyMemoryPerCore) {
	*out = *in
	in.MemoryMinMax.DeepCopyInto(&out.MemoryMinMax)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizingPolicyMemoryPerCore.
func (in *SizingPolicyMemoryPerCore) DeepCopy() *SizingPolicyMemoryPerCore {
	if in == nil {
		return nil
	}
	out := new(SizingPolicyMemoryPerCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineClass) DeepCopyInto(out *VirtualMachineClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineClass.
func (in *VirtualMachineClass) DeepCopy() *VirtualMachineClass {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineClassList) DeepCopyInto(out *VirtualMachineClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineClassList.
func (in *VirtualMachineClassList) DeepCopy() *VirtualMachineClassList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineClassSpec) DeepCopyInto(out *VirtualMachineClassSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CPU.DeepCopyInto(&out.CPU)
	if in.SizingPolicies != nil {
		in, out := &in.SizingPolicies, &out.SizingPolicies
		*out = make([]SizingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineClassSpec.
func (in *VirtualMachineClassSpec) DeepCopy() *VirtualMachineClassSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineClassStatus) DeepCopyInto(out *VirtualMachineClassStatus) {
	*out = *in
	in.CpuFeatures.DeepCopyInto(&out.CpuFeatures)
	if in.AvailableNodes != nil {
		in, out := &in.AvailableNodes, &out.AvailableNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxAllocatableResources != nil {
		in, out := &in.MaxAllocatableResources, &out.MaxAllocatableResources
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineClassStatus.
func (in *VirtualMachineClassStatus) DeepCopy() *VirtualMachineClassStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineClassStatus)
	in.DeepCopyInto(out)
	return out
}
