# Copyright 2025 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Daily CVE tests"
on:
  schedule:
    # Run at 2:00 every night (UTC).
    - cron: "0 02 * * *"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "release version in semver minor format (example: 1.68) or specified tag from dev registry"
        required: false
      scan_several_latest_releases:
        description: "Scan several latest releases"
        required: false
        default: false
        type: boolean

concurrency:
  group: cve-daily

jobs:
  cve_scan_daily:
    permissions:
      contents: read
      id-token: write
    name: Trivy images check
    runs-on: [self-hosted, large]
    steps:
      - uses: actions/checkout@v4

      - name: Set vars
        id: set_vars
        run: |
          if [ "${{ github.event.inputs.scan_several_latest_releases }}" = "true" ]; then
            echo "multiscan=True" >> $GITHUB_OUTPUT
          else
            echo "multiscan=False" >> $GITHUB_OUTPUT
          fi

      - name: Split repository name
        id: split
        env:
          REPO: ${{ github.repository }}
        run: echo "name=${REPO##*/}" >> $GITHUB_OUTPUT

      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://seguro.flant.com
          path: github
          role: "${{ steps.split.outputs.name }}"
          method: jwt
          jwtGithubAudience: github-access-aud
          secrets: |
            projects/data/101ceaca-97cd-462f-aed5-070d9b9de175/registry_host DECKHOUSE_DEV_REGISTRY_HOST | DECKHOUSE_DEV_REGISTRY_HOST ;
            projects/data/101ceaca-97cd-462f-aed5-070d9b9de175/dev-registry/writetoken login | DECKHOUSE_DEV_REGISTRY_USER ;
            projects/data/101ceaca-97cd-462f-aed5-070d9b9de175/dev-registry/writetoken password | DECKHOUSE_DEV_REGISTRY_PASSWORD ;
            projects/data/101ceaca-97cd-462f-aed5-070d9b9de175/registry_host DECKHOUSE_READ_REGISTRY_HOST | PROD_READ_REGISTRY ;
            projects/data/101ceaca-97cd-462f-aed5-070d9b9de175/ssdlc-registry-read-license login | PROD_READ_REGISTRY_USER ;
            projects/data/101ceaca-97cd-462f-aed5-070d9b9de175/ssdlc-registry-read-license password | PROD_READ_REGISTRY_PASSWORD ;
            projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets DD_TOKEN | DD_TOKEN ;
            projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets DD_URL | DD_URL ;
            projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets CVE_TEST_SSH_PRIVATE_KEY | CVE_TEST_SSH_PRIVATE_KEY ;
            projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets CVE_TEST_REPO_GIT | CVE_TEST_REPO_GIT ;
            projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets DECKHOUSE_PRIVATE_REPO | DECKHOUSE_PRIVATE_REPO ;
            projects/data/b050f3bd-733f-4746-9640-9df80d484074/CODEOWNERS_REPO_TOKEN CODEOWNERS_REPO_TOKEN | CODEOWNERS_REPO_TOKEN ;

      - uses: deckhouse/modules-actions/cve_scan@v11
        with:
          source_tag: ${{ github.event.inputs.tag_name || 'main' }}
          case: "External Modules"
          external_module_name: ${{ vars.MODULE_NAME }}
          dd_url: ${{ steps.secrets.outputs.DD_URL }}
          dd_token: ${{ steps.secrets.outputs.DD_TOKEN }}
          prod_registry: ${{ steps.secrets.outputs.PROD_READ_REGISTRY }}
          prod_registry_user: ${{ steps.secrets.outputs.PROD_READ_REGISTRY_USER }}
          prod_registry_password: ${{ steps.secrets.outputs.PROD_READ_REGISTRY_PASSWORD }}
          dev_registry: ${{ steps.secrets.outputs.DECKHOUSE_DEV_REGISTRY_HOST }}
          dev_registry_user: ${{ steps.secrets.outputs.DECKHOUSE_DEV_REGISTRY_USER }}
          dev_registry_password: ${{ steps.secrets.outputs.DECKHOUSE_DEV_REGISTRY_PASSWORD }}
          deckhouse_private_repo: ${{ steps.secrets.outputs.DECKHOUSE_PRIVATE_REPO }}
          codeowners_repo_token: ${{ steps.secrets.outputs.CODEOWNERS_REPO_TOKEN }}
          cve_test_repo_git: ${{ steps.secrets.outputs.CVE_TEST_REPO_GIT }}
          cve_ssh_private_key: ${{ steps.secrets.outputs.CVE_TEST_SSH_PRIVATE_KEY }}
          trivy_reports_log_output: "1"
          latest_releases_amount: 5
          scan_several_latest_releases: ${{ steps.set_vars.outputs.multiscan }}
