# Copyright 2025 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: E2E Matrix Tests (bootstrap)

env:
  BRANCH: main
  VIRTUALIZATION_TAG: main
  DECKHOUSE_TAG: main
  DEFAULT_USER: ubuntu
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    branches:
      - main
      - feat/ci/nightly-e2e-test-nested-env

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  bootstrap:
    name: Bootstrap cluster
    runs-on: ubuntu-latest
    outputs:
      kubeconfig-content: ${{ steps.generate-kubeconfig.outputs.config }}
    steps:
      - uses: actions/checkout@v4
        # with:
        #   ref: ${{ env.BRANCH }}

      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

          REGISTRY=$(base64 -d <<< ${{secrets.DEV_REGISTRY_DOCKER_CFG}} | jq '.auths | to_entries | .[] | .key' -r)
          USERNAME=$(base64 -d <<< ${{ secrets.DEV_REGISTRY_DOCKER_CFG }} | jq '.auths | to_entries | .[] | .value.auth' -r | base64 -d | cut -d ':' -f1)
          PASSWORD=$(base64 -d <<< ${{ secrets.DEV_REGISTRY_DOCKER_CFG }} | jq '.auths | to_entries | .[] | .value.auth' -r | base64 -d | cut -d ':' -f2)

          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
          echo "username=$USERNAME" >> $GITHUB_OUTPUT
          echo "password=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Install htpasswd utility
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2-utils

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup d8
        uses: ./.github/actions/install-d8

      - name: Log in to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.vars.outputs.registry }}
          username: ${{ steps.vars.outputs.username }}
          password: ${{ steps.vars.outputs.password }}

      - name: Configure kubectl via azure/k8s-set-context@v4
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          context: e2e-cluster-nightly-e2e-virt-sa
          kubeconfig: ${{ secrets.VIRT_E2E_NIGHTLY_SA_TOKEN }}

      - name: Generate values.yaml
        run: |
          defaultStorageClass=$(kubectl get storageclass -o json \
            | jq -r '.items[] | select(.metadata.annotations."storageclass.kubernetes.io/is-default-class" == "true") | .metadata.name')

          cat <<EOF > test/dvp-over-dvp/values.yaml
          namespace: nightly-e2e-${{ steps.vars.outputs.sha_short }}
          storageClass: ${defaultStorageClass}
          nfsSC: nightly-nfs-${{ steps.vars.outputs.sha_short }}
          clusterConfigurationPrefix: tst-dhctl
          sa: dkp-sa
          deckhouse:
            tag: ${{ env.DECKHOUSE_TAG }}
            kubernetesVersion: Automatic
            registryDockerCfg: ${{ secrets.DEV_REGISTRY_DOCKER_CFG }}
          virtualization:
            enabled: false
            tag: ${{ env.VIRTUALIZATION_TAG }}
          image:
            url: https://89d64382-20df-4581-8cc7-80df331f67fa.selstorage.ru/ubuntu/noble-server-cloudimg-amd64.img
            defaultUser: ${{ env.DEFAULT_USER }}
            bootloader: BIOS
          ingressHosts:
            - api
            - grafana
            - dex
            - prometheus
            - console
            - virtualization
          instances:
            masterNodes:
              count: 1
              cores: 8
              coreFraction: 50%
              memory: 14Gi
            additionalNodes:
              - name: worker
                count: 3
                cores: 10
                coreFraction: 25%
                memory: 8Gi
                nodeType: CloudEphemeral
          EOF

      - name: Bootstrap cluster
        run: |
          cd test/dvp-over-dvp
          task install
      - name: Create vmbda for workers
        run: |
          cd test/dvp-over-dvp
          chmod +x ./vmbda/attach-vmbda.sh

          echo "Create vmbda for workers"
          ./vmbda/attach-vmbda.sh "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo "End create vmbda for workers"
          
          echo "Pods"
          kubectl get pods -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo ""

          echo "VMs"
          kubectl get vm -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo ""
          
          echo "VDs"
          kubectl get vd -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo ""
          
          echo "VMBDAs"
          kubectl get vmbda -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
      
      - name: Get info about nested master VM
        run: |
          cd test/dvp-over-dvp
          namespace=nightly-e2e-${{ steps.vars.outputs.sha_short }}
          nested_master=$(kubectl -n $namespace get vm -l dvp.deckhouse.io/node-group=master -o jsonpath="{.items[0].metadata.name}")

          d8 k get vm -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo ""

          echo "login to master"
          echo "os-release master"
          d8 v ssh -i ./tmp/ssh/cloud \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.nightly-e2e-${{ steps.vars.outputs.sha_short }} \
            -c 'cat /etc/os-release'
          echo ""
          
          echo "hostname master"
          d8 v ssh -i ./tmp/ssh/cloud  \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.nightly-e2e-${{ steps.vars.outputs.sha_short }} \
            -c 'hostname'
      
      - name: Generate nested kubeconfig
        id: generate-kubeconfig
        env:
          kubeConfigPath: tmp/kube.config
        run: |
          NAMESPACE=nightly-e2e-${{ steps.vars.outputs.sha_short }}
          nested_master=$(kubectl -n $NAMESPACE get vm -l dvp.deckhouse.io/node-group=master -o jsonpath="{.items[0].metadata.name}")

          d8vssh() {
            local cmd="$1"
            echo "$cmd - 1 arg"
            echo "$@ - all arg"

            d8 v ssh -i ./tmp/ssh/cloud  \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.$NAMESPACE \
            -c "$cmd"

            echo "d8vssh $1 - done"
          }
          
          d8vscp() {
            local source=$1
            local dest=$2
            d8 v scp -i ./tmp/ssh/cloud  \
              --local-ssh=true \
              --local-ssh-opts="-o StrictHostKeyChecking=no" \
              --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
              $source $dest
            echo "d8vscp: $source -> $dest - done"
          }

          cd test/dvp-over-dvp
          
          echo "Copy script for generating kubeconfig in nested cluster"
          echo "copy nested-sa-config/gen-sa.sh to master"
          d8vscp "./nested-sa-config/gen-sa.sh" "${{ env.DEFAULT_USER }}@${nested_master}.${NAMESPACE}:/tmp/gen-sa.sh"
          echo ""
          d8vscp "./tools/deckhouse-queue.sh" "${{ env.DEFAULT_USER }}@${nested_master}.${NAMESPACE}:/tmp/deckhouse-queue.sh"
          echo ""

          echo "chmod +x /tmp/gen-sa.sh"
          
          # d8vssh "-c 'chmod +x /tmp/gen-sa.sh'"
          d8 v ssh -i ./tmp/ssh/cloud \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.${NAMESPACE} \
            -c 'chmod +x /tmp/gen-sa.sh; chmod +x /tmp/deckhouse-queue.sh'
          # echo "'chmod +x /tmp/gen-sa.sh' - done"
          echo ""

          echo "==="
          d8 v ssh -i ./tmp/ssh/cloud  \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.${NAMESPACE} \
            -c 'ls -la /tmp/'
          echo "==="

          
          # ----------
          echo "check d8 queue"
          d8 v ssh -i ./tmp/ssh/cloud  \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.${NAMESPACE} \
            -c '/tmp/deckhouse-queue.sh'
          # ----------
          
            echo "Generate kube conf in nested cluster"
          echo "run nested-sa-config/gen-sa.sh"
          
          # "Usage: gen-sa.sh <SA_NAME> <CLUSTER_PREFIX> <CLUSTER_NAME> [FILE_NAME]"
          echo "==="
          echo "-- -c 'sudo /tmp/gen-sa.sh nested-sa nested nested-e2e /${{ env.kubeConfigPath }}' --"
          echo "==="
          
          d8 v ssh -i ./tmp/ssh/cloud \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.$NAMESPACE \
            -c 'sudo /tmp/gen-sa.sh nested-sa nested nested-e2e /${{ env.kubeConfigPath }}'

          echo "'sudo /tmp/gen-sa.sh nested-sa nested nested-e2e /${{ env.kubeConfigPath }}' - done"
          echo ""
          
          echo "copy kubeconfig to runner"
          d8vscp "${{ env.DEFAULT_USER }}@${nested_master}.$NAMESPACE:/${{ env.kubeConfigPath }}" "${{ env.kubeConfigPath }}"

          echo "=== nested cluster via api get nodes ==="
          echo "sudo chown 1001:1001 ${{ env.kubeConfigPath }}"
          sudo chown 1001:1001 ${{ env.kubeConfigPath }}
          echo "sudo chmod 600 ${{ env.kubeConfigPath }}"
          sudo chmod 600 ${{ env.kubeConfigPath }}
          echo "rights - done"

          echo "-----"
          echo "cat ${{ env.kubeConfigPath }}"
          cat ${{ env.kubeConfigPath }}
          echo "-----"
          echo ""

          echo "-----"
          CONFIG=$(cat ${{ env.kubeConfigPath }} | base64 -w 0)
          CONFIG=$(echo $CONFIG | base64 -w 0)
          echo "$CONFIG"
          echo "-----"
          echo "config=$CONFIG" >> $GITHUB_OUTPUT

          echo "cat ${{ env.kubeConfigPath }} - done"

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        if: always()
        with:
          name: generated-files
          path: |
            test/dvp-over-dvp/tmp
            test/dvp-over-dvp/values.yaml

          overwrite: true
          include-hidden-files: true
          retention-days: 1
      # - name: Add annotation with the URL
      #   run: |
      #     ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload.outputs.artifact-id }}"
      #     echo "::notice title=Artifact Uploaded::Artifact available at: $ARTIFACT_URL"

  configure-storage:
    name: Configure storage
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v4
      
      
      - name: Restore kubeconfig from output
        run: |
          mkdir -p ~/.kube
          echo "get kubeconfig-content"
          echo "${{ needs.bootstrap.outputs.kubeconfig-content }}"
          echo "${{ needs.bootstrap.outputs.kubeconfig-content }}" | base64 -d | base64 -d > ~/.kube/config
          echo "---"
          echo "Show paths and files content"
          ls -la ~/.kube
          cat ~/.kube/config
          chmod 600 ~/.kube/config
          echo "-- end Show paths and files content --"
          kubectl config get-contexts
          kubectl config view
          # ----------
          PING_HOST=$(yq e '.clusters[0].cluster.server' ~/.kube/config | sed 's|https://||')
          echo "ping $PING_HOST"
          ping -c 5 $PING_HOST
          # ----------
          echo "curl -v $PING_HOST"
          curl -v $PING_HOST
          # ----------
          echo "kubectl get nodes"
          kubectl config use-context nested-e2e-nested-sa
          kubectl get nodes

  undeploy-infra:
    name: Undeploy infra
    runs-on: ubuntu-latest
    needs:
      - bootstrap
      - configure-storage
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install htpasswd utility
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2-utils
      
      - name: Setup d8
        uses: ./.github/actions/install-d8
      
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: generated-files
          path: test/dvp-over-dvp/
      
      - name: Show paths and files content
        run: |
          ls -la test/dvp-over-dvp/tmp
          ls -la test/dvp-over-dvp/tmp/
          cat test/dvp-over-dvp/values.yaml | tail -n +8
      
      - name: Configure kubectl via azure/k8s-set-context@v4
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          context: e2e-cluster-nightly-e2e-virt-sa
          kubeconfig: ${{ secrets.VIRT_E2E_NIGHTLY_SA_TOKEN }}
          
      - name: infra-undeploy
        run: |
          cd test/dvp-over-dvp
          task infra-undeploy
