# Copyright 2025 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: E2E Matrix Tests (bootstrap)

env:
  BRANCH: main
  VIRTUALIZATION_TAG: main
  DECKHOUSE_TAG: main
  DEFAULT_USER: ubuntu
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    branches:
      - main
      - feat/ci/nightly-e2e-test-nested-env

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  bootstrap:
    name: Bootstrap cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #   ref: ${{ env.BRANCH }}

      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

          REGISTRY=$(base64 -d <<< ${{secrets.DEV_REGISTRY_DOCKER_CFG}} | jq '.auths | to_entries | .[] | .key' -r)
          USERNAME=$(base64 -d <<< ${{ secrets.DEV_REGISTRY_DOCKER_CFG }} | jq '.auths | to_entries | .[] | .value.auth' -r | base64 -d | cut -d ':' -f1)
          PASSWORD=$(base64 -d <<< ${{ secrets.DEV_REGISTRY_DOCKER_CFG }} | jq '.auths | to_entries | .[] | .value.auth' -r | base64 -d | cut -d ':' -f2)

          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
          echo "username=$USERNAME" >> $GITHUB_OUTPUT
          echo "password=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Install htpasswd utility
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2-utils

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup d8
        uses: ./.github/actions/install-d8

      - name: Log in to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.vars.outputs.registry }}
          username: ${{ steps.vars.outputs.username }}
          password: ${{ steps.vars.outputs.password }}

      - name: Configure kubectl via azure/k8s-set-context@v4
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          context: e2e-cluster-nightly-e2e-virt-sa
          kubeconfig: ${{ secrets.VIRT_E2E_NIGHTLY_SA_TOKEN }}

      - name: Generate values.yaml
        run: |
          defaultStorageClass=$(kubectl get storageclass -o json \
            | jq -r '.items[] | select(.metadata.annotations."storageclass.kubernetes.io/is-default-class" == "true") | .metadata.name')

          cat <<EOF > test/dvp-over-dvp/values.yaml
          namespace: nightly-e2e-${{ steps.vars.outputs.sha_short }}
          storageClass: ${defaultStorageClass}
          clusterConfigurationPrefix: tst-dhctl
          sa: dkp-sa
          deckhouse:
            tag: ${{ env.DECKHOUSE_TAG }}
            kubernetesVersion: Automatic
            registryDockerCfg: ${{ secrets.DEV_REGISTRY_DOCKER_CFG }}
          virtualization:
            tag: ${{ env.VIRTUALIZATION_TAG }}
          image:
            url: https://89d64382-20df-4581-8cc7-80df331f67fa.selstorage.ru/ubuntu/noble-server-cloudimg-amd64.img
            defaultUser: ${{ env.DEFAULT_USER }}
            bootloader: BIOS
          ingressHosts:
            - api
            - grafana
            - dex
            - prometheus
            - console
            - virtualization
          instances:
            masterNodes:
              count: 1
              cores: 8
              coreFraction: 50%
              memory: 14Gi
            additionalNodes:
              - name: worker
                count: 3
                cores: 10
                coreFraction: 25%
                memory: 8Gi
                nodeType: CloudEphemeral
          EOF

      - name: Bootstrap cluster
        run: |
          cd test/dvp-over-dvp
          task install
      - name: Create vmbda for workers
        run: |
          cd test/dvp-over-dvp
          chmod +x ./vmbda/attach-vmbda.sh

          echo "Create vmbda for workers"
          ./vmbda/attach-vmbda.sh "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo "End create vmbda for workers"
          
          echo "Pods"
          kubectl get pods -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo ""

          echo "VMs"
          kubectl get vm -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo ""
          
          echo "VDs"
          kubectl get vd -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo ""
          
          echo "VMBDAs"
          kubectl get vmbda -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
      
      - name: Get info about nested master VM
        run: |
          cd test/dvp-over-dvp
          nested_master=$(kubectl -n nightly-e2e-${{ steps.vars.outputs.sha_short }} get vm -l dvp.deckhouse.io/node-group=master -o jsonpath="{.items[0].metadata.name}")

          d8 k get vm -n "nightly-e2e-${{ steps.vars.outputs.sha_short }}"
          echo ""

          echo "login to master"
          echo "os-release master"
          d8 v ssh -i ./tmp/ssh/cloud \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.nightly-e2e-${{ steps.vars.outputs.sha_short }} \
            -c 'cat /etc/os-release'
          echo ""
          
          echo "hostname master"
          d8 v ssh -i ./tmp/ssh/cloud  \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.nightly-e2e-${{ steps.vars.outputs.sha_short }} \
            -c 'hostname'
      
      - name: Copy script for gen nested kubeconfig
        run: |
          nested_master=$(kubectl -n nightly-e2e-${{ steps.vars.outputs.sha_short }} get vm -l dvp.deckhouse.io/node-group=master -o jsonpath="{.items[0].metadata.name}")

          d8vssh() {
            echo "$1 - 1 arg"
            echo "$2 - 2 arg"
            echo "$3 - 3 arg"
            echo "--------"
            echo "$@ - all args"

            d8 v ssh -i ./tmp/ssh/cloud  \
            --local-ssh=true \
            --local-ssh-opts="-o StrictHostKeyChecking=no" \
            --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
            ${{ env.DEFAULT_USER }}@${nested_master}.nightly-e2e-${{ steps.vars.outputs.sha_short }} \
            $@
          }
          
          d8vscp() {
            d8 v scp -i ./tmp/ssh/cloud  \
              --local-ssh=true \
              --local-ssh-opts="-o StrictHostKeyChecking=no" \
              --local-ssh-opts="-o UserKnownHostsFile=/dev/null" \
              $@
          }

          cd test/dvp-over-dvp
          # task configure:cluster:sa

          echo "copy nested-sa-config/gen-sa.sh to master"
          d8vscp ./nested-sa-config/gen-sa.sh ${{ env.DEFAULT_USER }}@${nested_master}.nightly-e2e-${{ steps.vars.outputs.sha_short }}:/tmp/gen-sa.sh
          echo ""

          echo "chmod nested-sa-config/gen-sa.sh"
          d8vssh "-c 'chmod +x /tmp/gen-sa.sh'"
          echo "d8vssh -c 'chmod +x /tmp/gen-sa.sh' - done"
          echo ""

          echo "run nested-sa-config/gen-sa.sh"
          d8vssh "-c 'sudo /tmp/gen-sa.sh'"
          echo "d8vssh -c 'sudo /tmp/gen-sa.sh' - done"
          echo ""
          
          echo "copy kubeconfig to runner"
          d8vscp ${{ env.DEFAULT_USER }}@${nested_master}.nightly-e2e-${{ steps.vars.outputs.sha_short }}:/tmp/kube.config ./tmp/kube.config

          echo "=== nestedt cluster via api get nodes ==="
          kubectl --kubeconfig=./tmp/kube.config get nodes
          echo ""

      - name: infra-undeploy
        if: ${{ always() }}
        run: |
          cd test/dvp-over-dvp
          task infra-undeploy
