on:
  pull_request:
    types: [ opened, edited, synchronize ]
    branches:
      - main
      - cicd/check-no_cyrillic
#  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  no_cyrillic:
    runs-on: ubuntu-latest
    name: check cytillic
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run git diff
        run: |
          echo $(git diff --name-only origin/main origin/${GITHUB_HEAD_REF} | grep -E '\.(go|md|yaml|yml)$' | grep -Pq "[\p{Cyrillic}]")