apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
{{- if eq (include "virtualization.rbacv2_new_scheme" .) "true" }}
  name: d8:namespace-capability:virtualization:view_secrets
  annotations:
    en.meta.deckhouse.io/title: "Virtualization: view secrets"
    ru.meta.deckhouse.io/title: "Виртуализация: просмотр секретов"
    en.meta.deckhouse.io/description: "Read Secrets in a namespace, including the cloud-init and sysprep data of virtual machines."
    ru.meta.deckhouse.io/description: "Чтение Secret в пространстве имён, в том числе данных cloud-init и sysprep виртуальных машин."
  labels:
    heritage: deckhouse
    module: virtualization
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/scope: namespace
    rbac.deckhouse.io/capability: "namespace-capability.virtualization.view_secrets"
    rbac.deckhouse.io/aggregate-to-namespace-as: user
{{- else }}
  name: d8:use:capability:virtualization:view_secrets
  labels:
    heritage: deckhouse
    module: virtualization
    rbac.deckhouse.io/aggregate-to-virtualization-as: user
    rbac.deckhouse.io/kind: use
{{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
